### ISSUE TITLE
Assert failure after dismantling a port

### ISSUE THREAD

**Issue by tppq** [widelands/widelands#3544]
Dismantling the port may crash the game. Probably related to wares in transit.

Trace:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff63dc535 in __GI_abort () at abort.c:79
#2  0x00007ffff63dc40f in __assert_fail_base (
    fmt=0x7fffedd7f97d "%s%s%s:%u: %s%sVäite ”%s” ei pidä paikkaansa.\n%n", 
    assertion=0x555557c26e20 "dest", file=0x555557c269a0 "../src/economy/portdock.cc", line=392, 
    function=<optimized out>) at assert.c:92
#3  0x00007ffff63ea102 in __GI___assert_fail (assertion=0x555557c26e20 "dest", 
    file=0x555557c269a0 "../src/economy/portdock.cc", line=392, 
    function=0x555557c28080 <Widelands::PortDock::load_wares(Widelands::Game&, Widelands::Ship&)::__PRETTY_FUNCTION__> "void Widelands::PortDock::load_wares(Widelands::Game&, Widelands::Ship&)") at assert.c:101
#4  0x000055555729d5f1 in Widelands::PortDock::load_wares (this=0x611000166380, game=..., ship=...)
    at ../src/economy/portdock.cc:392
#5  0x000055555729d070 in Widelands::PortDock::ship_arrived (this=0x611000166380, game=..., ship=...)
    at ../src/economy/portdock.cc:376
#6  0x0000555556f989b5 in Widelands::Ship::ship_update_transport (this=0x61200022edc0, game=..., state=...)
    at ../src/logic/map_objects/tribes/ship.cc:315
#7  0x0000555556f98251 in Widelands::Ship::ship_update (this=0x61200022edc0, game=..., state=...)
    at ../src/logic/map_objects/tribes/ship.cc:265
#8  0x0000555556ea9b7c in Widelands::Bob::do_act (this=0x61200022edc0, game=...)
    at ../src/logic/map_objects/bob.cc:194

**To Reproduce**
- Build some ships and ports, and initiate traffic between them
- Dismantle a port.
- Wait a while.

**Expected behavior**
The wares should be rerouted (if possible), else economy splits

**Version:**
 - OS: Debian 10 64-bit
 - Widelands Version:r24255 / bcca1c2a414ea9d4ba894f85b83ea20401c1d021

**Comment by tppq** [comment]
[wl_autosave_00.wgf.gz](https://github.com/widelands/widelands/files/3720674/wl_autosave_00.wgf.gz)

Savegame.

**Comment by tppq** [comment]
[anothersavegame.zip](https://github.com/widelands/widelands/files/3721534/anothersavegame.zip)

Another savegame: The previous one was after a dismantle, this is an earlier one.
