### ISSUE TITLE
Expedition builder doesn't arrive

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3938]
See [the replay](https://github.com/widelands/widelands/files/4758016/expedition_builder_bug.zip):
- At 3:31:31 an expedition is started at the main port.
- At 3:34:55 the builder's icon is darkened (indicating he is coming).
- At 3:39:36 it's lightened again (as if he's missing).
- He never arrives, even after several hours when there are many builders sitting in warehouses.

Interestingly, when I reload [a save made while it was in this broken state](https://github.com/widelands/widelands/files/4758146/385.wgf.zip), the problem disappears: the builder arrives and the expedition can proceed. So saving and reloading fixes it.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: r24628[7747702@master] (Release)

I *always* run into bugs when playing this map. Maybe someday I'll get to finish it ^^;

**Comment by Noordfrees** [comment]
Confirmed with the replay, will investigate…

**Comment by Noordfrees** [comment]
[Just taking notes…]
The builder, serial 3776, is located at 310×8 (portdock 198370) at assignment time. That is, this is the builder of a newly completed expedition port who is immediately reassigned to the expedition-in-preparation.
→ transfer route:
- 179118 (flag @ 310×9 with port on island No.3, cur loc)
- 37543 (flag @ 321×106 with port on island No.9, :frowning: )
- 6449 (flag @ 255×223 with main port, dest)

(Why does the builder want to take a route via that intermediate island??)
[will now try to follow his route…]
→ At 3:39:36 the worker suddenly leaves the portdock even though no ship has arrived yet – and his transfer is now changed to nullptr:
```
MO(3776,frisians_builder): [transfer]: Fail (without transfer)
```
(worker.cc:1482)
The request is still valid, count_==1, transfers_.size()==0 
→ So who cancelled the Transfer?
```
#0  Widelands::Worker::cancel_task_transfer(Widelands::Game&) (this=0x6120005be940, game=...) at ../src/logic/map_objects/tribes/worker.cc:1639
#1  0x000055555743b29a in Widelands::Transfer::~Transfer() (this=0x60700084b2b0, __in_chrg=<optimised out>) at ../src/economy/transfer.cc:74
#2  0x00005555573a3c8e in Widelands::Request::remove_transfer(unsigned int) (this=0x60e0002a1620, idx=0) at ../src/economy/request.cc:491
#3  0x00005555573a3a7c in Widelands::Request::cancel_transfer(unsigned int) (this=0x60e0002a1620, idx=0) at ../src/economy/request.cc:478
#4  0x00005555573a09ee in Widelands::Request::~Request() (this=0x60e0002a1620, __in_chrg=<optimised out>) at ../src/economy/request.cc:87
#5  0x00005555573a0a3e in Widelands::Request::~Request() (this=0x60e0002a1620, __in_chrg=<optimised out>) at ../src/economy/request.cc:88
#6  0x000055555701885d in std::default_delete<Widelands::Request>::operator()(Widelands::Request*) const (this=0x608000b16648, __ptr=0x60e0002a1620) at /usr/include/c++/10/bits/unique_ptr.h:84
#7  0x0000555557018dff in std::__uniq_ptr_impl<Widelands::Request, std::default_delete<Widelands::Request> >::reset(Widelands::Request*) (this=0x608000b16648, __p=0x0)
    at /usr/include/c++/10/bits/unique_ptr.h:181
#8  0x0000555557017142 in std::unique_ptr<Widelands::Request, std::default_delete<Widelands::Request> >::reset(Widelands::Request*) (this=0x608000b16648, __p=0xcc6e96b9)
    at /usr/include/c++/10/bits/unique_ptr.h:455
#9  0x000055555744b1bc in Widelands::WorkersQueue::remove_from_economy(Widelands::Economy&) (this=0x608000b16620) at ../src/economy/workers_queue.cc:99
#10 0x000055555735f8c3 in Widelands::ExpeditionBootstrap::set_economy(Widelands::Economy*, Widelands::WareWorker) (this=0x6060003d3280, new_economy=0x0, type=Widelands::wwWORKER)
    at ../src/economy/expedition_bootstrap.cc:245
#11 0x000055555739741f in Widelands::PortDock::set_economy(Widelands::Economy*, Widelands::WareWorker) (this=0x610000364940, e=0x0, type=Widelands::wwWORKER) at ../src/economy/portdock.cc:142
#12 0x000055555710b36f in Widelands::Warehouse::set_economy(Widelands::Economy*, Widelands::WareWorker) (this=0x6160001e2780, e=0x0, type=Widelands::wwWORKER) at ../src/logic/map_objects/tribes/warehouse.cc:805
#13 0x000055555737ed86 in Widelands::Flag::set_economy(Widelands::Economy*, Widelands::WareWorker) (this=0x6130001080c0, e=0x0, type=Widelands::wwWORKER) at ../src/economy/flag.cc:202
#14 0x000055555732cd40 in Widelands::Economy::do_remove_flag(Widelands::Flag&) (this=0x61100175c040, flag=...) at ../src/economy/economy.cc:291
#15 0x000055555732cb4e in Widelands::Economy::remove_flag(Widelands::Flag&) (this=0x61100175c040, flag=...) at ../src/economy/economy.cc:278
#16 0x000055555732fbee in Widelands::Economy::split(std::set<Widelands::OPtr<Widelands::Flag>, std::less<Widelands::OPtr<Widelands::Flag> >, std::allocator<Widelands::OPtr<Widelands::Flag> > > const&)
    (this=0x61100175c040, flags=std::set with 256 elements = {...}) at ../src/economy/economy.cc:559
#17 0x000055555732bc10 in Widelands::Economy::check_splits() (this=0x61100175c040) at ../src/economy/economy.cc:165
#18 0x000055555733519d in Widelands::Economy::balance(unsigned int) (this=0x61100175c040, timerid=11016) at ../src/economy/economy.cc:1056
#19 0x000055555744dcc5 in Widelands::CmdCallEconomyBalance::execute(Widelands::Game&) (this=0x6030030655f0, game=...) at ../src/economy/cmd_call_economy_balance.cc:50
#20 0x000055555748941f in Widelands::CmdQueue::run_queue(int, unsigned int&) (this=0x7fffffff91d8, interval=1672, game_time_var=@0x7fffffff8928: 13175476) at ../src/logic/cmd_queue.cc:121
#21 0x00005555567cc0d1 in Widelands::Game::think() (this=0x7fffffff8920) at ../src/logic/game.cc:592
#22 0x0000555556c4b1db in InteractiveBase::think() (this=0x625000154100) at ../src/wui/interactive_base.cc:700
#23 0x0000555556a8a536 in UI::Panel::do_think() (this=0x625000154100) at ../src/ui_basic/panel.cc:506
#24 0x0000555556a879e1 in UI::Panel::do_run() (this=0x625000154100) at ../src/ui_basic/panel.cc:195
#25 0x0000555556449ca0 in UI::Panel::run<UI::Panel::Returncodes>() (this=0x625000154100) at ../src/ui_basic/panel.h:100
#26 0x00005555567cb7f8 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffffff8920, start_game_type=Widelands::Game::Loaded, script_to_run="", replay=true, prefix_for_replays="replay") at ../src/logic/game.cc:562
#27 0x0000555556435a19 in WLApplication::replay() (this=0x6120000001c0) at ../src/wlapplication.cc:1503
#28 0x0000555556430218 in WLApplication::mainmenu() (this=0x6120000001c0) at ../src/wlapplication.cc:1160
#29 0x00005555564202ce in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:493
#30 0x000055555641ba82 in main(int, char**) (argc=2, argv=0x7fffffffde78) at ../src/main.cc:42
(gdb) 
```

So apparently a flag or road is being removed, causing an economy split. WorkerQueues reset their Request to nullptr on this occasion and re-initialize it later. So the unassignment of the builder is correct. The question now is why no new builder is assigned later…
