### ISSUE TITLE
MP Scenario Smugglers segfaults when loading the scenario

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3940]
Just wanted to reproduce issue #3927 but the scenario doesn't start at all:

~~~~
....
[Host]: starting up.
[NetHost] Opening a listening IPv4 socket on TCP port 7396
[NetHost] Opening a listening IPv6 socket on TCP port 7396
[NetHost] Starting to listen for network connections
[NetHost] Starting networking thread
[LAN] Started an IPv4 socket on UDP port 7395.
[LAN] Started an IPv6 socket on UDP port 7395.
[LAN] Will broadcast to 127.0.0.1.
[LAN] Will broadcast to 192.168.178.255.
[LAN] Will broadcast for IPv6.
Map/Save is a directory! No way for making it available a.t.m.!
widelands: /home/kaputtnik/Quellcode/widelands-repo/widelands/src/ui_basic/panel.cc:313: virtual void UI::Panel::set_desired_size(int, int): Zusicherung »w >= 0« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)
~~~~

**To Reproduce**
1. Choose Multiplayer -> LAN/Direct IP
2. Click on: New Game -> Map
3. Choose: Multiplayer Scenarios -> Smugglers
4. Click OK

**Version:**
 - archlinux
 - Widelands Version: edec161@master] (Debug)

**Additional context**
As far i have tested the crash happens only with 'Smugglers', not with 'Island Hopping' or any other map.

**Comment by Noordfrees** [comment]
Confirmed.
```
widelands: ../src/ui_basic/panel.cc:313: virtual void UI::Panel::set_desired_size(int, int): Assertion `w >= 0' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6a86859 in __GI_abort () at abort.c:79
#2  0x00007ffff6a86729 in __assert_fail_base
    (fmt=0x7ffff6c1c588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555557a9f300 "w >= 0", file=0x555557a9ef60 "../src/ui_basic/panel.cc", line=313, function=<optimised out>) at assert.c:92
#3  0x00007ffff6a97f36 in __GI___assert_fail
    (assertion=0x555557a9f300 "w >= 0", file=0x555557a9ef60 "../src/ui_basic/panel.cc", line=313, function=0x555557a9f220 "virtual void UI::Panel::set_desired_size(int, int)") at assert.c:101
#4  0x0000555556a8896a in UI::Panel::set_desired_size(int, int) (this=0x6120005878c0, w=-10, h=20) at ../src/ui_basic/panel.cc:313
#5  0x0000555556a0dbb7 in UI::Box::update_desired_size() (this=0x6120005878c0) at ../src/ui_basic/box.cc:122
#6  0x0000555556a0fa69 in UI::Box::add(UI::Panel*, UI::Box::Resizing, UI::Align) (this=0x6120005878c0, panel=0x61100073db00, resizing=UI::Box::Resizing::kAlign, align=UI::Align::kLeft)
    at ../src/ui_basic/box.cc:297
#7  0x0000555557743b6d in UI::SuggestedTeamsBox::show(std::vector<std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >, std::allocator<std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > > > > const&)
    (this=0x6130001e8980, suggested_teams=std::vector of length 1, capacity 1 = {...}) at ../src/wui/suggested_teams_box.cc:124
#8  0x0000555556b0dd3c in FullscreenMenuLaunchMPG::load_map_info() (this=0x7fffffff49d0) at ../src/ui_fsmenu/launch_mpg.cc:618
#9  0x0000555556b08334 in FullscreenMenuLaunchMPG::refresh() (this=0x7fffffff49d0) at ../src/ui_fsmenu/launch_mpg.cc:411
#10 0x0000555556b07d9e in FullscreenMenuLaunchMPG::think() (this=0x7fffffff49d0) at ../src/ui_fsmenu/launch_mpg.cc:376
#11 0x0000555556a8a536 in UI::Panel::do_think() (this=0x7fffffff49d0) at ../src/ui_basic/panel.cc:506
#12 0x0000555556a879e1 in UI::Panel::do_run() (this=0x7fffffff49d0) at ../src/ui_basic/panel.cc:195
#13 0x0000555556447be2 in UI::Panel::run<FullscreenMenuBase::MenuTarget>() (this=0x7fffffff49d0) at ../src/ui_basic/panel.h:100
#14 0x0000555556929c05 in GameHost::run() (this=0x7fffffff61e0) at ../src/network/gamehost.cc:624
#15 0x0000555556431f17 in WLApplication::mainmenu_multiplayer() (this=0x6120000001c0) at ../src/wlapplication.cc:1318
#16 0x0000555556430204 in WLApplication::mainmenu() (this=0x6120000001c0) at ../src/wlapplication.cc:1157
#17 0x00005555564202ce in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:493
#18 0x000055555641ba82 in main(int, char**) (argc=2, argv=0x7fffffffde88) at ../src/main.cc:42
```
Perhaps related to #3928 

Edit: Since this happens only in debug builds I would not consider this critical though

**Comment by frankystone** [comment]
> Perhaps related to #3928

Yes, trying to use a map with recommended teams segfaults also.

**Comment by frankystone** [comment]
Duplicate with #3928
