### ISSUE TITLE
Assertion `!s.get_destination()' failed when a port is built

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3957]
Player 6 (orange AI) is building a port. After the port is completed in a release build saving fails with the following message:
```
GenericSaveHandler::save_file: data could not be written to file save/wl_autosave_00.wgf: Player 6: economy 8389 has no representative
```
In a debug build an assertion failure happens when the port is completed:
```
Message: adding warehouse for player 6 at (153, 24)
widelands: ../src/economy/shipping_schedule.cc:317: void Widelands::ShippingSchedule::ship_added(Widelands::Game&, Widelands::Ship&): Assertion `!s.get_destination()' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
0x00007ffff6588355 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6588355 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6571853 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff6571727 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007ffff6580936 in  () at /usr/lib/libc.so.6
#4  0x0000555557387e0b in Widelands::ShippingSchedule::ship_added(Widelands::Game&, Widelands::Ship&) (this=0x612000627e58, game=..., s=...)
    at ../src/economy/shipping_schedule.cc:317
#5  0x00005555573673ac in Widelands::ShipFleet::add_ship(Widelands::EditorGameBase&, Widelands::Ship*) (this=0x612000627dc0, egbase=..., ship=0x6120008b2ac0)
    at ../src/economy/ship_fleet.cc:393
#6  0x00005555573658b5 in Widelands::ShipFleet::merge(Widelands::EditorGameBase&, Widelands::ShipFleet*) (this=0x612000627dc0, egbase=..., other=0x612000ac3840)
    at ../src/economy/ship_fleet.cc:215
#7  0x00005555573657e2 in Widelands::ShipFleet::merge(Widelands::EditorGameBase&, Widelands::ShipFleet*) (this=0x612000ac3840, egbase=..., other=0x612000627dc0)
    at ../src/economy/ship_fleet.cc:201
#8  0x000055555736548e in Widelands::ShipFleet::find_other_fleet(Widelands::EditorGameBase&) (this=0x612000627dc0, egbase=...) at ../src/economy/ship_fleet.cc:179
#9  0x0000555557364992 in Widelands::ShipFleet::init(Widelands::EditorGameBase&) (this=0x612000627dc0, egbase=...) at ../src/economy/ship_fleet.cc:109
#10 0x0000555557340c8e in Widelands::PortDock::init_fleet(Widelands::EditorGameBase&) (this=0x6100001d5340, egbase=...) at ../src/economy/portdock.cc:165
#11 0x0000555557340b1b in Widelands::PortDock::init(Widelands::EditorGameBase&) (this=0x6100001d5340, egbase=...) at ../src/economy/portdock.cc:153
#12 0x00005555570bff03 in Widelands::Warehouse::init_portdock(Widelands::EditorGameBase&) (this=0x616000113780, egbase=...)
    at ../src/logic/map_objects/tribes/warehouse.cc:623
#13 0x00005555570bf034 in Widelands::Warehouse::init(Widelands::EditorGameBase&) (this=0x616000113780, egbase=...)
    at ../src/logic/map_objects/tribes/warehouse.cc:575
#14 0x0000555556f8c36f in Widelands::BuildingDescr::create(Widelands::EditorGameBase&, Widelands::Player*, Widelands::Coords, bool, bool, std::vector<std::pair<unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) const
    (this=0x6170002c2d00, egbase=..., owner=0x61900007e980, pos=..., construct=false, loading=false, former_buildings=std::vector of length 1, capacity 1 = {...})
    at ../src/logic/map_objects/tribes/building.cc:245
#15 0x0000555556fb6276 in Widelands::ConstructionSite::cleanup(Widelands::EditorGameBase&) (this=0x616000371a80, egbase=...)
    at ../src/logic/map_objects/tribes/constructionsite.cc:283
#16 0x0000555556f72570 in Widelands::MapObject::remove(Widelands::EditorGameBase&) (this=0x616000371a80, egbase=...) at ../src/logic/map_objects/map_object.cc:502
#17 0x0000555556f725f5 in Widelands::MapObject::destroy(Widelands::EditorGameBase&) (this=0x616000371a80, egbase=...) at ../src/logic/map_objects/map_object.cc:518
#18 0x0000555556f8ee51 in Widelands::Building::destroy(Widelands::EditorGameBase&) (this=0x616000371a80, egbase=...)
    at ../src/logic/map_objects/tribes/building.cc:546
#19 0x0000555556f6c62f in Widelands::CmdDestroyMapObject::execute(Widelands::Game&) (this=0x602001c3cb90, game=...) at ../src/logic/map_objects/map_object.cc:58
#20 0x000055555742e239 in Widelands::CmdQueue::run_queue(int, unsigned int&) (this=0x7fffffff87f8, interval=74, game_time_var=@0x7fffffff7f48: 52334443)
    at ../src/logic/cmd_queue.cc:121
#21 0x00005555567aac85 in Widelands::Game::think() (this=0x7fffffff7f40) at ../src/logic/game.cc:592
#22 0x0000555556c164df in InteractiveBase::think() (this=0x625000640100) at ../src/wui/interactive_base.cc:700
#23 0x0000555556c9e75d in InteractivePlayer::think() (this=0x625000640100) at ../src/wui/interactive_player.cc:315
#24 0x0000555556a5b63c in UI::Panel::do_think() (this=0x625000640100) at ../src/ui_basic/panel.cc:506
#25 0x0000555556a58b57 in UI::Panel::do_run() (this=0x625000640100) at ../src/ui_basic/panel.cc:195
#26 0x000055555643b812 in UI::Panel::run<UI::Panel::Returncodes>() (this=0x625000640100) at ../src/ui_basic/panel.h:100
#27 0x00005555567aa410 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (this=0x7fffffff7f40, start_game_type=Widelands::Game::Loaded, script_to_run="", replay=false, prefix_for_replays="single_player") at ../src/logic/game.cc:562
#28 0x00005555567a89ed in Widelands::Game::run_load_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffffff7f40, filename="save/port_built_save_failure.wgf.zip", script_to_run="")
    at ../src/logic/game.cc:417
#29 0x00005555564268bc in WLApplication::load_game() (this=0x6120000001c0) at ../src/wlapplication.cc:1423
#30 0x00005555564237bd in WLApplication::mainmenu_singleplayer() (this=0x6120000001c0) at ../src/wlapplication.cc:1252
#31 0x00005555564227d5 in WLApplication::mainmenu() (this=0x6120000001c0) at ../src/wlapplication.cc:1154
#32 0x0000555556412d34 in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:493
#33 0x000055555640e62e in main(int, char**) (argc=2, argv=0x7fffffffdf68) at ../src/main.cc:42
```
**Save just before the port is completed:**
[port_built_save_failure.wgf.zip](https://github.com/widelands/widelands/files/4842782/port_built_save_failure.wgf.zip)

**Screenshot:**
![shot0018](https://user-images.githubusercontent.com/4470900/85955043-3f75f600-b97c-11ea-8c1d-85725cd84570.png)

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: r24837[75189d8@amazons]

**Comment by Noordfrees** [comment]
During a fleet merge, the same ship (Agilaz) is being added to the new fleet *twice*.
```
Widelands::ShipFleet::merge (this=0x612000379540, egbase=..., other=0x612000520840) at ../src/economy/ship_fleet.cc:212
212		while (!other->ships_.empty()) {
(gdb) print this
$7 = (Widelands::ShipFleet * const) 0x612000379540
(gdb) print other
$8 = (Widelands::ShipFleet *) 0x612000520840
(gdb) print ships_
$9 = std::vector of length 2, capacity 2 = {0x612000138dc0, 0x612000138dc0}
(gdb) print other->ships_
$10 = std::vector of length 1, capacity 4 = {0x6120003f4b40}
```

This is already the case when the savegame is loaded, before the port is completed:
```
(gdb) break Ship::log_general_info(Widelands::EditorGameBase const&) const 
Haltepunkt 2 at 0x5555570704f6: file ../src/logic/map_objects/tribes/ship.cc, line 1047.
(gdb) c
Continuing.

Thread 1 "widelands" hit Breakpoint 2, Widelands::Ship::log_general_info (this=0x2, egbase=...) at ../src/logic/map_objects/tribes/ship.cc:1047
1047	void Ship::log_general_info(const EditorGameBase& egbase) const {
(gdb) n
1048		Bob::log_general_info(egbase);
(gdb) print owner().player_number()
$1 = 6 '\006'
(gdb) print fleet_
$2 = (Widelands::ShipFleet *) 0x612000455440
(gdb) print fleet_->ports_
$3 = std::vector of length 0, capacity 0
(gdb) print fleet_->ships_
$4 = std::vector of length 3, capacity 4 = {0x612000472540, 0x6120004a95c0, 0x6120004a95c0}
```

It would be interesting to know how the ship came to be added to the fleet twice in the first place. Do you have a replay that shows the construction of player 6's *Agilaz*?

**Comment by Niektory** [comment]
> It would be interesting to know how the ship came to be added to the fleet twice in the first place. Do you have a replay that shows the construction of player 6's _Agilaz_?

I'll look for it.

**Comment by Niektory** [comment]
[Agilaz_built_replay.zip](https://github.com/widelands/widelands/files/4843025/Agilaz_built_replay.zip)

7:27:25 - Player 6's Agilaz is built
7:40:55 - Player 6's Agilaz begins expedition
9:47:04 - Player 6's port is destroyed
