### ISSUE TITLE
bad lexical cast error on startup

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4057]
Since d2369aaa5e30c06f75c79f1a58322c100c88ef5a Widelands crashes on startup.
Error message:
```
Graphics: OpenGL: ShadingLanguage: "4.60 NVIDIA"
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_lexical_cast>'
  what():  bad lexical cast: source type value could not be interpreted as target
```
Offending line:
https://github.com/widelands/widelands/blob/1b68d968fd3b3e12adce2685d15f647239487834/src/graphic/gl/initialize.cc#L239-L240

Probably the "NVIDIA" in the version string is causing the error.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: from d2369aaa5e30c06f75c79f1a58322c100c88ef5a to 1b68d96, both debug and release
 - Boost: 1.72.0

**Log+backtrace:**
```
This is Widelands Version 1.0~git24720[1b68d96@HEAD] (Debug)
Set home directory: /home/mnj/.widelands
Set configuration file: /home/mnj/.widelands/config
Realpath: /home/mnj/widelands/data
Adding directory: /home/mnj/widelands/data
selected language: (system language)
using locale en_US.utf8
Byte order: little-endian
Graphics: Try to set Videomode 1920x1200
Graphics: OpenGL: Version "4.6.0 NVIDIA 430.64"
Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 0
Graphics: SDL_GL_BUFFER_SIZE is 24
Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 24
Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 16
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 16
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 16
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 16
Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 16384
Graphics: OpenGL: ShadingLanguage: "4.60 NVIDIA"
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_lexical_cast>'
  what():  bad lexical cast: source type value could not be interpreted as target

Program received signal SIGABRT, Aborted.
0x00007ffff6588355 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6588355 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6571853 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff690a86a in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff6916d8a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff6916df7 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff691709e in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*))
    (obj=<optimized out>, tinfo=0x5555583cde68 <typeinfo for boost::wrapexcept<boost::bad_lexical_cast>>, dest=0x55555662be16 <boost::wrapexcept<boost::bad_lexical_cast>::~wrapexcept()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x000055555662a0be in boost::throw_exception<boost::bad_lexical_cast>(boost::bad_lexical_cast const&) (e=...) at /usr/include/boost/throw_exception.hpp:70
#7  0x0000555556900fa6 in boost::conversion::detail::throw_bad_cast<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>() ()
    at /usr/include/boost/lexical_cast/bad_lexical_cast.hpp:92
#8  0x00005555568fe2b9 in boost::lexical_cast<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (arg="60 NVIDIA") at /usr/include/boost/lexical_cast.hpp:42
#9  0x00005555572f3e60 in Gl::initialize(Gl::Trace const&, SDL_Window*, int*) (sdl_window=0x611000024a80, max_texture_size=0x7fffffffd4f0)
    at ../src/graphic/gl/initialize.cc:240
#10 0x0000555556687c56 in Graphic::initialize(Graphic::TraceGl const&, int, int, bool)
    (this=0x60b00001aa80, trace_gl=@0x7fffffffda30: Graphic::TraceGl::kNo, window_mode_w=1920, window_mode_h=1200, init_fullscreen=false)
    at ../src/graphic/graphic.cc:90
#11 0x0000555556441505 in WLApplication::WLApplication(int, char const* const*) (this=0x6120000001c0, argc=2, argv=0x7fffffffdf38) at ../src/wlapplication.cc:387
#12 0x000055555644069a in WLApplication::get(int, char const**) (argc=2, argv=0x7fffffffdf38) at ../src/wlapplication.cc:298
#13 0x000055555643e68e in main(int, char**) (argc=2, argv=0x7fffffffdf38) at ../src/main.cc:40
```

**Comment by frankystone** [comment]
Same for me...
