### ISSUE TITLE
Starting a LAN game with AIs as spectator crashes

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4093]
The game crashes when a LAN game with AIs is started with the host spectating.

**To Reproduce**
1. Host a new LAN game.
2. Pick any map, Firegames for example.
3. Set yourself to spectator and all players to normal AI. 
4. Start the game.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: 1.0~git24752[b08c22a@HEAD] (both release and debug)

**Backtrace**
```
Game: Writing Interactive Player Data ... 
Thread 1 "widelands" received signal SIGSEGV, Segmentation fault.
0x0000555556d150c7 in std::_Rb_tree<Widelands::Ship*, std::pair<Widelands::Ship* const, Widelands::Coords>, std::_Select1st<std::pair<Widelands::Ship* const, Widelands::Coords> >, std::less<Widelands::Ship*>, std::allocator<std::pair<Widelands::Ship* const, Widelands::Coords> > >::begin (this=0x2618)
    at /usr/include/c++/10.1.0/bits/stl_tree.h:1003
1003	      { return iterator(this->_M_impl._M_header._M_left); }
(gdb) bt
#0  0x0000555556d150c7 in std::_Rb_tree<Widelands::Ship*, std::pair<Widelands::Ship* const, Widelands::Coords>, std::_Select1st<std::pair<Widelands::Ship* const, Widelands::Coords> >, std::less<Widelands::Ship*>, std::allocator<std::pair<Widelands::Ship* const, Widelands::Coords> > >::begin() (this=0x2618)
    at /usr/include/c++/10.1.0/bits/stl_tree.h:1003
#1  0x0000555556d135ac in std::map<Widelands::Ship*, Widelands::Coords, std::less<Widelands::Ship*>, std::allocator<std::pair<Widelands::Ship* const, Widelands::Coords> > >::begin() (this=0x2618) at /usr/include/c++/10.1.0/bits/stl_map.h:357
#2  0x0000555557499ff1 in Widelands::GameInteractivePlayerPacket::write(FileSystem&, Widelands::Game&, Widelands::MapObjectSaver*) (this=0x7fffffff1960, fs=..., 
    game=..., mos=0x61900079e580) at ../src/game_io/game_interactive_player_packet.cc:161
#3  0x000055555748f1f6 in Widelands::GameSaver::save() (this=0x7fffffff1db0) at ../src/game_io/game_saver.cc:115
#4  0x00005555568a686b in operator()(FileSystem&) const (__closure=0x7fffffff2d90, fs=...) at ../src/logic/save_handler.cc:248
#5  0x00005555568a74a7 in std::__invoke_impl<void, SaveHandler::save_game(Widelands::Game&, const string&, std::string*)::<lambda(FileSystem&)>&, FileSystem&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/10.1.0/bits/invoke.h:60
#6  0x00005555568a732a in std::__invoke_r<void, SaveHandler::save_game(Widelands::Game&, const string&, std::string*)::<lambda(FileSystem&)>&, FileSystem&>(struct {...} &) (__fn=...) at /usr/include/c++/10.1.0/bits/invoke.h:153
#7  0x00005555568a7180 in std::_Function_handler<void(FileSystem&), SaveHandler::save_game(Widelands::Game&, const string&, std::string*)::<lambda(FileSystem&)> >::_M_invoke(const std::_Any_data &, FileSystem &) (__functor=..., __args#0=...) at /usr/include/c++/10.1.0/bits/std_function.h:291
#8  0x0000555556f95e2b in std::function<void (FileSystem&)>::operator()(FileSystem&) const (this=0x7fffffff2d90, __args#0=...)
    at /usr/include/c++/10.1.0/bits/std_function.h:622
#9  0x0000555556f90333 in GenericSaveHandler::save_file() (this=0x7fffffff2d90) at ../src/logic/generic_save_handler.cc:108
#10 0x0000555556f911a6 in GenericSaveHandler::save() (this=0x7fffffff2d90) at ../src/logic/generic_save_handler.cc:166
#11 0x00005555568a6b86 in SaveHandler::save_game(Widelands::Game&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)
    (this=0x7fffffff4728, game=..., complete_filename="replays/2020-08-10T22.39.44_nethost.wrpl.wgf", error_str=0x7fffffff3030) at ../src/logic/save_handler.cc:251
#12 0x00005555568a03ce in Widelands::ReplayWriter::ReplayWriter(Widelands::Game&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x6040042dc0d0, game=..., filename="replays/2020-08-10T22.39.44_nethost.wrpl") at ../src/logic/replay.cc:228
#13 0x000055555680b89a in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (this=0x7fffffff3e40, start_game_type=Widelands::Game::StartGameType::kMap, script_to_run="", replay=false, prefix_for_replays="nethost")
    at ../src/logic/game.cc:540
#14 0x000055555696bb96 in GameHost::run() (this=0x7fffffff60c0) at ../src/network/gamehost.cc:708
#15 0x00005555564666c4 in WLApplication::mainmenu_multiplayer() (this=0x6120000001c0) at ../src/wlapplication.cc:1342
#16 0x0000555556464861 in WLApplication::mainmenu() (this=0x6120000001c0) at ../src/wlapplication.cc:1172
#17 0x0000555556454c80 in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:494
#18 0x000055555645068e in main(int, char**) (argc=2, argv=0x7fffffffdf48) at ../src/main.cc:42
```

**Comment by Niektory** [comment]
ab814efb6405192141f4c302d850094a78000223 is the first bad commit (Show buildhelp semi-transparent on PreviouslySeen nodes #4083)
