### ISSUE TITLE
Assertion `ware_filled_ < ware_capacity_' failed.

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4103]
The game crashed in a match between two AIs. It also crashes when watching the replay. The failed assertion:
```
widelands: ../src/economy/flag.cc:447: void Widelands::Flag::add_ware(Widelands::EditorGameBase&, Widelands::WareInstance&): Assertion `ware_filled_ < ware_capacity_' failed.
```
In a release build a heap-buffer-overflow happens instead.

**To Reproduce**
1. Watch [the replay](https://github.com/widelands/widelands/files/5058583/fetch_pending_ware_crash.zip).
2. Resume after it ends.
3. The game crashes at 23:27.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: The original crash happened when testing #4095, but it's also reproducible in 1.0~git24752[b08c22a@master]

**Backtrace**
```
#0  0x00007ffff656b355 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6554853 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff6554727 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007ffff6563936 in  () at /usr/lib/libc.so.6
#4  0x00005555573b45f8 in Widelands::Flag::add_ware(Widelands::EditorGameBase&, Widelands::WareInstance&) (this=0x613000187cc0, egbase=..., ware=...)
    at ../src/economy/flag.cc:447
#5  0x00005555571790f3 in Widelands::Worker::fugitive_update(Widelands::Game&, Widelands::Bob::State&) (this=0x6120008e42c0, game=..., state=...)
    at ../src/logic/map_objects/tribes/worker.cc:2612
#6  0x0000555556f97490 in Widelands::Bob::do_act(Widelands::Game&) (this=0x6120008e42c0, game=...) at ../src/logic/map_objects/bob.cc:194
#7  0x0000555556f971f8 in Widelands::Bob::act(Widelands::Game&, unsigned int) (this=0x6120008e42c0, game=..., data=1821) at ../src/logic/map_objects/bob.cc:180
#8  0x0000555556fe1989 in Widelands::CmdAct::execute(Widelands::Game&) (this=0x603000b230f0, game=...) at ../src/logic/map_objects/map_object.cc:107
#9  0x00005555574b6653 in Widelands::CmdQueue::run_queue(int, unsigned int&) (this=0x7fffffff90d0, interval=67, game_time_var=@0x7fffffff8818: 1407594)
    at ../src/logic/cmd_queue.cc:122
#10 0x000055555680c33b in Widelands::Game::think() (this=0x7fffffff8810) at ../src/logic/game.cc:598
#11 0x0000555556c810d8 in InteractiveBase::think() (this=0x62500028f100) at ../src/wui/interactive_base.cc:693
#12 0x0000555556ac4d78 in UI::Panel::do_think() (this=0x62500028f100) at ../src/ui_basic/panel.cc:506
#13 0x0000555556ac2293 in UI::Panel::do_run() (this=0x62500028f100) at ../src/ui_basic/panel.cc:195
#14 0x000055555647d702 in UI::Panel::run<UI::Panel::Returncodes>() (this=0x62500028f100) at ../src/ui_basic/panel.h:100
#15 0x000055555680bac6 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (this=0x7fffffff8810, start_game_type=Widelands::Game::StartGameType::kSaveGame, script_to_run="", replay=true, prefix_for_replays="replay")
    at ../src/logic/game.cc:568
#16 0x0000555556469fb9 in WLApplication::replay() (this=0x6120000001c0) at ../src/wlapplication.cc:1532
#17 0x0000555556464875 in WLApplication::mainmenu() (this=0x6120000001c0) at ../src/wlapplication.cc:1175
#18 0x0000555556454c80 in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:494
#19 0x000055555645068e in main(int, char**) (argc=2, argv=0x7fffffffdf48) at ../src/main.cc:42
```

**Comment by Noordfrees** [comment]
Not fair! Side-effect of #4076 which was merged just one day ago ;)
