### ISSUE TITLE
ware statistic segfaults

### ISSUE THREAD

**Issue by spth** [widelands/widelands#4172]
Today, on my Debian GNU/Linux testing system on amd64, I got current widelands from git, compiled using compile -r, started a new game, played a bit, then tried to look at the ware statistic.

widelands crashes, and the crash is reproducible using the save at
http://www.colecovision.eu/stuff/segfault-max.wgf

**Comment by Noordfrees** [comment]
Confirmed. Backtrace:
```
=================================================================
==35232==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x000000b44cf3 bp 0x7ffe3ca1c7d0 sp 0x7ffe3ca1c7a0 T0)
==35232==The signal is caused by a READ memory access.
==35232==Hint: address points to the zero page.
    #0 0xb44cf3 in std::vector<unsigned int, std::allocator<unsigned int> >::size() const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:916:40
    #1 0x14656bd in WuiPlotArea::get_game_time() const /home/benedikt/wl/splashscreen/build/../src/wui/plot_area.cc:346:50
    #2 0x1466a2b in WuiPlotArea::get_game_time_id() /home/benedikt/wl/splashscreen/build/../src/wui/plot_area.cc:398:23
    #3 0x146f70d in WuiPlotArea::register_plot_data(unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > const*, RGBColor) /home/benedikt/wl/splashscreen/build/../src/wui/plot_area.cc:587:2
    #4 0x128c859 in WareStatisticsMenu::WareStatisticsMenu(InteractivePlayer&, UI::UniqueWindow::Registry&) /home/benedikt/wl/splashscreen/build/../src/wui/ware_statistics_menu.cc:162:21
    #5 0x11a54f3 in InteractivePlayer::add_statistics_menu()::$_11::operator()() const /home/benedikt/wl/splashscreen/build/../src/wui/interactive_player.cc:285:7
    #6 0x11a546c in void std::__invoke_impl<void, InteractivePlayer::add_statistics_menu()::$_11&>(std::__invoke_other, InteractivePlayer::add_statistics_menu()::$_11&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14
    #7 0x11a540c in std::enable_if<__and_<std::is_void<void>, std::__is_invocable<InteractivePlayer::add_statistics_menu()::$_11&> >::value, void>::type std::__invoke_r<void, InteractivePlayer::add_statistics_menu()::$_11&>(InteractivePlayer::add_statistics_menu()::$_11&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:153:7
    #8 0x11a52bc in std::_Function_handler<void (), InteractivePlayer::add_statistics_menu()::$_11>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:291:9
    #9 0x8f84b0 in std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14
    #10 0xf37ca2 in UI::UniqueWindow::Registry::toggle() /home/benedikt/wl/splashscreen/build/../src/ui_basic/unique_window.cc:68:3
    #11 0x119d02a in InteractivePlayer::handle_key(bool, SDL_Keysym) /home/benedikt/wl/splashscreen/build/../src/wui/interactive_player.cc:614:30
    #12 0xebb529 in UI::Panel::do_key(bool, SDL_Keysym) /home/benedikt/wl/splashscreen/build/../src/ui_basic/panel.cc:1022:6
    #13 0xeaeb19 in UI::Panel::ui_key(bool, SDL_Keysym) /home/benedikt/wl/splashscreen/build/../src/ui_basic/panel.cc:1229:12
    #14 0x5d0f6c in WLApplication::handle_input(InputCallback const*) /home/benedikt/wl/splashscreen/build/../src/wlapplication.cc:615:15
    #15 0xead4d9 in UI::Panel::do_run() /home/benedikt/wl/splashscreen/build/../src/ui_basic/panel.cc:189:8
    #16 0x5e7024 in UI::Panel::Returncodes UI::Panel::run<UI::Panel::Returncodes>() /home/benedikt/wl/splashscreen/build/../src/ui_basic/panel.h:102:34
    #17 0xb2b014 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/benedikt/wl/splashscreen/build/../src/logic/game.cc:552:15
    #18 0xb2e310 in Widelands::Game::run_load_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/benedikt/wl/splashscreen/build/../src/logic/game.cc:404:23
    #19 0x5db3ee in WLApplication::load_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /home/benedikt/wl/splashscreen/build/../src/wlapplication.cc:1430:12
    #20 0x5cdec8 in WLApplication::mainmenu() /home/benedikt/wl/splashscreen/build/../src/wlapplication.cc:1217:6
    #21 0x5cbd89 in WLApplication::run() /home/benedikt/wl/splashscreen/build/../src/wlapplication.cc:487:3
    #22 0x5bfd5a in main /home/benedikt/wl/splashscreen/build/../src/main.cc:42:10
    #23 0x7f2d47f4c0b2 in __libc_start_main /build/glibc-YYA7BZ/glibc-2.31/csu/../csu/libc-start.c:308:16
    #24 0x51551d in _start (/home/benedikt/wl/splashscreen/widelands+0x51551d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:916:40 in std::vector<unsigned int, std::allocator<unsigned int> >::size() const
==35232==ABORTING
```

**Comment by spth** [comment]
On another system (also Debian GNU/Linux testing amd64, but a desktop, as the previous report was from a notebook), I compiled the same widelands version from git, started a new game on the same map. It took a bit longer this time, but now I also see the ware statistics crash there.

**Comment by gunchleoc** [comment]
Thanks for testing some more. The attached pull request should fix it.
