### ISSUE TITLE
Map is loaded on Load Map screen before pressing OK

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4509]
Selecting a map in the "Load Map" window in the editor loads it immediately (without pressing OK).

It can also lead to a crash if a minimap window is opened at the time:

```
widelands: ../src/graphic/texture.cc:244: void Texture::set_pixel(uint16_t, uint16_t, const RGBAColor&): Assertion `x < width()' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
0x00007ffff4f4a615 in raise () from /usr/lib/libc.so.6

(gdb) bt
#0  0x00007ffff4f4a615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff4f33862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff4f33747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff4f42bf6 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055555663b277 in Texture::set_pixel (this=0x606001ebea60, x=256, y=128, color=...) at ../src/graphic/texture.cc:244
#5  0x0000555556ea27c7 in (anonymous namespace)::do_draw_minimap (texture=..., egbase=..., player=0x0, top_left=..., 
    layers=(MiniMapLayer::Terrain | MiniMapLayer::Owner | MiniMapLayer::Flag | MiniMapLayer::Road | MiniMapLayer::Building | MiniMapLayer::ViewWindow), 
    draw_full=false, rows_drawn=0x61f0001a0b40) at ../src/graphic/minimap_renderer.cc:220
#6  0x0000555556ea38bd in draw_minimap_static (texture=..., egbase=..., player=0x0, 
    layers=(MiniMapLayer::Terrain | MiniMapLayer::Owner | MiniMapLayer::Flag | MiniMapLayer::Road | MiniMapLayer::Building | MiniMapLayer::ViewWindow), 
    draw_full=false, rows_drawn=0x61f0001a0b40) at ../src/graphic/minimap_renderer.cc:287
#7  0x00005555563e453e in MiniMap::View::draw (this=0x61f0001a0a38, dst=...) at ../src/wui/minimap.cc:66
#8  0x0000555556131143 in UI::Panel::do_draw_inner (this=0x61f0001a0a38, dst=...) at ../src/ui_basic/panel.cc:882
#9  0x0000555556131b8d in UI::Panel::do_draw (this=0x61f0001a0a38, dst=...) at ../src/ui_basic/panel.cc:922
#10 0x000055555613118e in UI::Panel::do_draw_inner (this=0x61f0001a0880, dst=...) at ../src/ui_basic/panel.cc:886
#11 0x0000555556131b8d in UI::Panel::do_draw (this=0x61f0001a0880, dst=...) at ../src/ui_basic/panel.cc:922
#12 0x000055555613118e in UI::Panel::do_draw_inner (this=0x625000d7c900, dst=...) at ../src/ui_basic/panel.cc:886
#13 0x0000555556131b8d in UI::Panel::do_draw (this=0x625000d7c900, dst=...) at ../src/ui_basic/panel.cc:922
#14 0x000055555612b060 in UI::Panel::do_run (this=0x625000d7c900) at ../src/ui_basic/panel.cc:208
#15 0x0000555555a23306 in UI::Panel::run<UI::Panel::Returncodes> (this=0x625000d7c900) at ../src/ui_basic/panel.h:104
#16 0x0000555555adf6c0 in EditorInteractive::run_editor (init=EditorInteractive::Init::kLoad, filename="", script_to_run="")
    at ../src/editor/editorinteractive.cc:1021
#17 0x0000555555a04a97 in WLApplication::mainmenu (this=0x6120000001c0) at ../src/wlapplication.cc:1249
#18 0x00005555559f3ef6 in WLApplication::run (this=0x6120000001c0) at ../src/wlapplication.cc:500
#19 0x00005555559ee71e in main (argc=2, argv=0x7fffffffdf28) at ../src/main.cc:47
```

**To reproduce:**
1. Open the editor.
2. Optionally open the minimap window.
3. Press Ctrl+L to open the Load Map window.
4. Select any map.
5. At this point the game may crash if you opened the minimap window in step 2.
6. Press Cancel.
7. The selected map will be loaded (but not fully, some things will be wrong).

**Version:**
 - OS: Manjaro 20.2
 - Widelands Version: 1.0~git25050[1878bf2@master] (Debug)

**Comment by Noordfrees** [comment]
Can you test if this also happens with #4464?

**Comment by Niektory** [comment]
Will do.

**Comment by Niektory** [comment]
I can't reproduce the problem with 2715202@addons (Debug), seems to be fixed there.
