### ISSUE TITLE
Error when closing the game: SupplyList::remove: not in list

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4533]
When quitting the game by closing the window the following error sometimes occurs:
```
terminate called after throwing an instance of 'WException'
  what():  [../src/economy/supply_list.cc:48] SupplyList::remove: not in list
```
I don't have a replay. It happened twice when playing this game: [Euro_Turk_12.wgf.zip](https://github.com/widelands/widelands/files/5580762/Euro_Turk_12.wgf.zip). Happened together with #4532, maybe related?

**Version:**
 - OS: Manjaro 20.2
 - Widelands Version: 1.0~git25070[fe4c1e3@HEAD] (Release)

**Comment by frankystone** [comment]
Once i got this error also. If i remember correctly i have tried to leave the game normally (not by closing the window) close after i conquered a foreign miltary site. Also played the map Europa.

Version: [a3ffba3@master] (Release)

**Comment by Niektory** [comment]
I got this by watching [this replay](https://github.com/widelands/widelands/files/5584811/SupplyList_crash_replay.zip) in a debug build until 6:24:00 and closing the game:
```
==31196==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61100164b4f8 at pc 0x555556b66eb9 bp 0x7fffffff7a00 sp 0x7fffffff79f0
READ of size 8 at 0x61100164b4f8 thread T0
    #0 0x555556b66eb8 in __gnu_cxx::__normal_iterator<Widelands::Supply**, std::vector<Widelands::Supply*, std::allocator<Widelands::Supply*> > >::__normal_iterator(Widelands::Supply** const&) /usr/include/c++/10.2.0/bits/stl_iterator.h:954
    #1 0x555556b66893 in std::vector<Widelands::Supply*, std::allocator<Widelands::Supply*> >::begin() /usr/include/c++/10.2.0/bits/stl_vector.h:812
    #2 0x555556b661e5 in Widelands::SupplyList::remove_supply(Widelands::Supply&) ../src/economy/supply_list.cc:39
    #3 0x555556a56dea in Widelands::Economy::remove_supply(Widelands::Supply&) ../src/economy/economy.cc:479
    #4 0x555556b6b83c in Widelands::IdleWareSupply::set_economy(Widelands::Economy*) ../src/economy/ware_instance.cc:92
    #5 0x555556b6b79f in Widelands::IdleWareSupply::~IdleWareSupply() ../src/economy/ware_instance.cc:83
    #6 0x555556b6b7c7 in Widelands::IdleWareSupply::~IdleWareSupply() ../src/economy/ware_instance.cc:84
    #7 0x555556b6c591 in Widelands::WareInstance::cleanup(Widelands::EditorGameBase&) ../src/economy/ware_instance.cc:214
    #8 0x5555566dad2f in Widelands::MapObject::remove(Widelands::EditorGameBase&) ../src/logic/map_objects/map_object.cc:540
    #9 0x5555566d5b09 in Widelands::ObjectManager::cleanup(Widelands::EditorGameBase&) ../src/logic/map_objects/map_object.cc:188
    #10 0x555555af7fe7 in Widelands::EditorGameBase::cleanup_objects() ../src/logic/editor_game_base.h:184
    #11 0x555555e44c66 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:656
    #12 0x555555a0bd8b in WLApplication::replay(FullscreenMenuMain*) ../src/wlapplication.cc:1629
    #13 0x555555a04524 in WLApplication::mainmenu() ../src/wlapplication.cc:1220
    #14 0x5555559f3ef5 in WLApplication::run() ../src/wlapplication.cc:500
    #15 0x5555559ee71d in main ../src/main.cc:47
    #16 0x7ffff4f35151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
    #17 0x5555559ee5ad in _start (/home/mnj/widelands/widelands+0x49a5ad)

Address 0x61100164b4f8 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/10.2.0/bits/stl_iterator.h:954 in __gnu_cxx::__normal_iterator<Widelands::Supply**, std::vector<Widelands::Supply*, std::allocator<Widelands::Supply*> > >::__normal_iterator(Widelands::Supply** const&)
Shadow bytes around the buggy address:
  0x0c22802c1640: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c1650: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c1660: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c1670: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c1680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c22802c1690: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c22802c16a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c16b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c16c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c16d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22802c16e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==31196==ABORTING
```

**Comment by Niektory** [comment]
Got the exception from the original post again when exiting the game after playing. Watching [the replay](https://github.com/widelands/widelands/files/5591138/SupplyList_segfault.zip) to the end with a release build and then exiting causes a segfault.
