### ISSUE TITLE
Crash when changing tabs in General Statistics

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4545]
**To Reproduce**
1. Start the first Empire campaign mission.
2. Press 'G' while the loading screen is shown.
3. Press the Workers button in the General Statistics window.
4. The game crashes.

**Version:**
 - OS: Manjaro 20.2
 - Widelands Version: 1.0~git25083[dd5c8b9@HEAD] (Debug)

**Backtrace**
```
widelands: ../src/wui/plot_area.cc:605: void WuiPlotArea::show_plot(unsigned int, bool): Assertion `plotdata_.count(id) == 1' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
0x00007ffff4eb4615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff4eb4615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff4e9d862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff4e9d747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff4eacbf6 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00005555566e425d in WuiPlotArea::show_plot (this=0x61a0005d0340, id=1, t=true) at ../src/wui/plot_area.cc:605
#5  0x00005555566b3ebe in GeneralStatisticsMenu::radiogroup_changed (this=0x61a0005d0080, id=1) at ../src/wui/general_statistics_menu.cc:241
#6  0x00005555566ae58a in operator() (__closure=0x60600088bca0, i=1) at ../src/wui/general_statistics_menu.cc:200
#7  0x00005555566b6720 in boost::detail::function::void_function_obj_invoker1<GeneralStatisticsMenu::GeneralStatisticsMenu(InteractiveGameBase&, GeneralStatisticsMenu::Registry&)::<lambda(int32_t)>, void, int>::invoke(boost::detail::function::function_buffer &, int) (function_obj_ptr=..., 
    a0=<error reading variable: Cannot access memory at address 0xffffffffffffffc0>) at /usr/include/boost/function/function_template.hpp:158
#8  0x00005555561bc8a1 in boost::function1<void, int>::operator() (this=0x60600088bc98, a0=1) at /usr/include/boost/function/function_template.hpp:763
#9  0x00005555561bc751 in boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (int)>, 0u, int&>(boost::function<void (int)>&, boost::signals2::detail::unsigned_meta_array<0u>, std::tuple<int&> const&, boost::enable_if<boost::is_void<boost::function<void (int)>::result_type>, void>::type*) const (this=0x7fffffff21a0, func=..., args=std::tuple containing = {...}) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:105
#10 0x00005555561bc6d6 in boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (int)>, int&, 1ul>(boost::function<void (int)>&, std::tuple<int&> const&, mpl_::size_t<1ul>) const (this=0x7fffffff21a0, func=..., args=std::tuple containing = {...})
    at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#11 0x00005555561bc634 in boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > const&) const (this=0x7fffffff2940, connectionBody=...)
    at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#12 0x00005555561bc3c9 in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> >::dereference() const (this=0x7fffffff2360)
    at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
#13 0x00005555561bc23c in boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > const&) (f=...)
    at /usr/include/boost/iterator/iterator_facade.hpp:550
#14 0x00005555561bc0aa in boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const
    (this=0x7fffffff2360) at /usr/include/boost/iterator/iterator_facade.hpp:656
#15 0x00005555561bb5b4 in boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> >) const (this=0x60200010c8f0, first=..., last=...) at /usr/include/boost/signals2/optional_last_value.hpp:57
#16 0x00005555561ba878 in boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int), boost::function<void (int)> >, boost::signals2::mutex> >) const (this=0x7fffffff25f0, combiner=..., first=<error reading variable: Cannot access memory at address 0xffffffffffffff60>, last=<error reading variable: Cannot access memory at address 0xffffffffffffffa0>) at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:64
#17 0x00005555561b9891 in boost::signals2::detail::signal_impl<void (int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (int)>, boost::function<void (boost::signals2::connection const&, int)>, boost::signals2::mutex>::operator()(int) (this=0x60400011b050, args#0=1) at /usr/include/boost/signals2/detail/signal_template.hpp:243
#18 0x00005555561b8fa1 in boost::signals2::signal<void (int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (int)>, boost::function<void (boost::signals2::connection const&, int)>, boost::signals2::mutex>::operator()(int) (this=0x61a0005d0498, args#0=1) at /usr/include/boost/signals2/detail/signal_template.hpp:722
#19 0x00005555561b8d7f in UI::Radiogroup::set_state (this=0x61a0005d0480, state=1) at ../src/ui_basic/radiobutton.cc:125
#20 0x00005555561b843a in UI::Radiobutton::button_clicked (this=0x6130001709c0) at ../src/ui_basic/radiobutton.cc:56
#21 0x0000555556141ccf in UI::Statebox::handle_mousepress (this=0x6130001709c0, btn=1 '\001') at ../src/ui_basic/checkbox.cc:207
#22 0x00005555561a495c in UI::Panel::do_mousepress (this=0x6130001709c0, btn=1 '\001', x=26, y=8) at ../src/ui_basic/panel.cc:991
#23 0x00005555561a48b5 in UI::Panel::do_mousepress (this=0x612000a51b40, btn=1 '\001', x=65, y=8) at ../src/ui_basic/panel.cc:986
#24 0x00005555561a48b5 in UI::Panel::do_mousepress (this=0x61a0005d0220, btn=1 '\001', x=65, y=188) at ../src/ui_basic/panel.cc:986
#25 0x00005555561a48b5 in UI::Panel::do_mousepress (this=0x61a0005d0080, btn=1 '\001', x=70, y=193) at ../src/ui_basic/panel.cc:986
#26 0x00005555561a48b5 in UI::Panel::do_mousepress (this=0x626000177100, btn=1 '\001', x=90, y=213) at ../src/ui_basic/panel.cc:986
#27 0x00005555561a618e in UI::Panel::ui_mousepress (button=1 '\001', x=90, y=213) at ../src/ui_basic/panel.cc:1189
#28 0x0000555555a3c646 in WLApplication::handle_mousebutton (this=0x6120000001c0, ev=..., cb=0x555557e57760 <UI::Panel::do_run()::input_callback>) at ../src/wlapplication.cc:768
#29 0x0000555555a3b5eb in WLApplication::handle_input (this=0x6120000001c0, cb=0x555557e57760 <UI::Panel::do_run()::input_callback>) at ../src/wlapplication.cc:683
#30 0x000055555619d7ac in UI::Panel::do_run (this=0x626000177100) at ../src/ui_basic/panel.cc:190
#31 0x0000555555a6a41e in UI::Panel::run<UI::Panel::Returncodes> (this=0x626000177100) at ../src/ui_basic/panel.h:104
#32 0x0000555555e9b883 in Widelands::Game::run (this=0x7fffffff3ce0, start_game_type=Widelands::Game::StartGameType::kSinglePlayerScenario, script_to_run="", replay=false, prefix_for_replays="single_player") at ../src/logic/game.cc:667
#33 0x0000555555e95867 in Widelands::Game::run_splayer_scenario_direct (this=0x7fffffff3ce0, mapname="campaigns/emp02.wmf", script_to_run="") at ../src/logic/game.cc:260
#34 0x0000555555a50f23 in WLApplication::campaign_game (this=0x6120000001c0, fsmm=...) at ../src/wlapplication.cc:1638
#35 0x0000555555a49f6f in WLApplication::mainmenu (this=0x6120000001c0) at ../src/wlapplication.cc:1248
#36 0x0000555555a396a6 in WLApplication::run (this=0x6120000001c0) at ../src/wlapplication.cc:543
#37 0x0000555555a3280e in main (argc=2, argv=0x7fffffffdf28) at ../src/main.cc:47
```

**Comment by Niektory** [comment]
The problem is that the General Statistics window only reads certain information about the game state that it assumes to be static in the constructor when it is created. If it is created before that information is fully set up it is not created in a usable state. Any changes to that information while the window is open also cause problems.

It needs to be somehow updated when the information changes. Or at least delay initialization until it is ready. I'm not sure how to handle it yet.
