### ISSUE TITLE
Game Crash randomly

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#4570]
widelands: ../src/logic/map_objects/bob.h:301: Widelands::Bob::State& Widelands::Bob::top_state(): Zusicherung »stack_.size()« nicht erfüllt.

I used this build with europeans tribe (as player tribe) and barbarians and empire as AI tribes on the build-in Europa 1.2 map in an endless game. I haven't changed the source code of the game. The game randomly crashes when the game time is above 24 hours. After a certain point in time, a saved game can no longer be loaded. The game crashes seconds after loading.

It should be noted that between the start of the game and the time of the crash I changed a few things in my tribe, such as production programs for workers and buildings or build / enhancement costs. I have no idea how that affects this bug.

**Comment by Noordfrees** [comment]
Regression of #3669 #4235 
Can you attach a deterministically failing savegame?

**Comment by MarkMcWire** [comment]
You can use the last savegame from forum. https://www.widelands.org/forum/attachment/bf4f909b40d71a91359ab761e793d643c5131c70/

To use it, you need my data folder from my fork. But I don't changed any files from other tribes, adding only my own.

**Comment by Noordfrees** [comment]
```
[00:05:27.801 real] INFO: TrainingSite::drop_stalled_soldiers: Kicking somebody out.
widelands: ../src/logic/map_objects/bob.h:301: Widelands::Bob::State &Widelands::Bob::top_state(): Assertion `stack_.size()' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff5864864 in __GI_abort () at abort.c:79
#2  0x00007ffff5864749 in __assert_fail_base
    (fmt=0x7ffff59f0458 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x2616520 <str> "stack_.size()", file=0x2616560 <str> "../src/logic/map_objects/bob.h", line=301, function=<optimised out>)
    at assert.c:92
#3  0x00007ffff5876a96 in __GI___assert_fail
    (assertion=0x2616520 <str> "stack_.size()", file=0x2616560 <str> "../src/logic/map_objects/bob.h", line=301, function=0x26165a0 <__PRETTY_FUNCTION__._ZN9Widelands3Bob9top_stateEv> "Widelands::Bob::State &Widelands::Bob::top_state()") at assert.c:101
#4  0x000000000166ab3c in Widelands::Bob::top_state() (this=0x61200055f6c0) at ../src/logic/map_objects/bob.h:301
#5  0x000000000165b753 in Widelands::Bob::do_pop_task(Widelands::Game&) (this=0x61200055f6c0, game=...) at ../src/logic/map_objects/bob.cc:248
#6  0x000000000165cbaf in Widelands::Bob::pop_task(Widelands::Game&) (this=0x61200055f6c0, game=...) at ../src/logic/map_objects/bob.cc:269
#7  0x000000000190af35 in Widelands::Worker::run_terraform(Widelands::Game&, Widelands::Bob::State&, Widelands::Worker::Action const&) (this=0x61200055f6c0, game=..., state=...)
    at ../src/logic/map_objects/tribes/worker.cc:1006
#8  0x0000000001917454 in Widelands::Worker::program_update(Widelands::Game&, Widelands::Bob::State&) (this=0x61200055f6c0, game=..., state=...) at ../src/logic/map_objects/tribes/worker.cc:2103
#9  0x000000000165bfdd in Widelands::Bob::do_act(Widelands::Game&) (this=0x61200055f6c0, game=...) at ../src/logic/map_objects/bob.cc:194
#10 0x000000000165bd6d in Widelands::Bob::act(Widelands::Game&, unsigned int) (this=0x61200055f6c0, game=..., data=90685) at ../src/logic/map_objects/bob.cc:180
#11 0x00000000016ffa15 in Widelands::CmdAct::execute(Widelands::Game&) (this=0x6030041530c0, game=...) at ../src/logic/map_objects/map_object.cc:106
#12 0x0000000001ce3249 in Widelands::CmdQueue::run_queue(Duration const&, Time&) (this=0x7fffffff5cb8, interval=..., game_time_var=...) at ../src/logic/cmd_queue.cc:122
#13 0x0000000000b94c78 in Widelands::Game::think() (this=0x7fffffff53a0) at ../src/logic/game.cc:699
#14 0x000000000126752d in InteractiveBase::think() (this=0x625000142900) at ../src/wui/interactive_base.cc:680
#15 0x000000000131601f in InteractivePlayer::think() (this=0x625000142900) at ../src/wui/interactive_player.cc:398
#16 0x0000000000f4ad97 in UI::Panel::do_think() (this=0x625000142900) at ../src/ui_basic/panel.cc:555
#17 0x0000000000f48cad in UI::Panel::do_run() (this=0x625000142900) at ../src/ui_basic/panel.cc:207
#18 0x0000000000663a85 in UI::Panel::run<UI::Panel::Returncodes>() (this=0x625000142900) at ../src/ui_basic/panel.h:104
#19 0x0000000000b8fc2c in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)Python Exception <class 'gdb.error'> Es gibt kein Mitglied mit dem Namen _M_dataplus.: 
Python Exception <class 'gdb.error'> Es gibt kein Mitglied mit dem Namen _M_dataplus.: 
 (this=0x7fffffff53a0, start_game_type=Widelands::Game::StartGameType::kSaveGame, script_to_run=, replay=false, prefix_for_replays=) at ../src/logic/game.cc:669
#20 0x0000000000b93cb4 in Widelands::Game::run_load_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)Python Exception <class 'gdb.error'> Es gibt kein Mitglied mit dem Namen _M_dataplus.: 
Python Exception <class 'gdb.error'> Es gibt kein Mitglied mit dem Namen _M_dataplus.: 
 (this=0x7fffffff53a0, filename=, script_to_run=) at ../src/logic/game.cc:447
#21 0x00000000006551f3 in WLApplication::load_game(FullscreenMenuMain&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x6120000001c0, 
    fsmm=..., filename=<unvollständiger Typ>) at ../src/wlapplication.cc:1591
#22 0x0000000000646cdd in WLApplication::mainmenu() (this=0x6120000001c0) at ../src/wlapplication.cc:1248
#23 0x0000000000644713 in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:543
#24 0x000000000063530b in main(int, char**) (argc=1, argv=0x7fffffffde88) at ../src/main.cc:47
```
Worker at 375×500 with empty stack; `state` is a `Widelands::Worker::taskProgram`; his location is a productionsite at 376×507

**Comment by MarkMcWire** [comment]
I demolished all the forester houses at these coordinates. Seems to have helped. The question is, how did his stack get empty?

**Comment by MarkMcWire** [comment]
After I deleted the forester's houses that contained the fault worker (with empty stack), the game continued to run for 20 hours without any problems.

Now it crashed again with the same error message.

See savegame in forum thread.

**Comment by Noordfrees** [comment]
The linked PR should fix it
