### ISSUE TITLE
Python error in translations update script

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4729]
The translations update script no longer works for me (neither before nor after the changes of #4728 by which I tried to fix it). The step that fails is the `update_translation_stats` program.
```
Fetching translation stats .Something went wrong:
Traceback (most recent call last):
  File "utils/update_translation_stats.py", line 140, in main
    result = generate_translation_stats(po_dir, output_file)
  File "utils/update_translation_stats.py", line 64, in generate_translation_stats
    if 'ERROR' in stats_output:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by frankystone** [comment]
This script is not python3 ready.

Will try to look into it.
