### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#4772]
**Describe the bug**
I had the game crash in multiplayer at the same point repeatedly. Does not matter if there are actual remote players connected or not. Even local user can be just spectator.

**To Reproduce**
1. Host multiplayer LAN game loading the attached savegame
2. You can set all players to AI
3. Start the game
4. After a few seconds, the game always crashes for me, without any warning or message

**Expected behavior**
Be able to play further ;)

**Screenshots**
not applicable

**Version:**
 - OS: antix / Debian buster + some backports
 - Widelands Version: Build 21 flatpak

**Additional context**
Neither CPU, nor memory usage is high. (Acer Swift 1 laptop with Pentium Silver N5000 CPU and 4GB RAM) Total memory usage is just above 1GB, of which Widelands uses about 700MB.
I don't understand flatpak's "black magic", so I don't know how to provide a debug log.

[vizgy_hoppa.wgf.gz](https://github.com/widelands/widelands/files/6143644/vizgy_hoppa.wgf.gz)

**Comment by Noordfrees** [comment]
Thank you for your bug report. The ASan output with build 21 says
```
=================================================================
==40884==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000070 (pc 0x564c0f967899 bp 0x7ffe6f66e740 sp 0x7ffe6f66e730 T0)
==40884==The signal is caused by a READ memory access.
==40884==Hint: address points to the zero page.
    #0 0x564c0f967899 in Widelands::PortDock::get_fleet() const ../src/economy/portdock.h:85
    #1 0x564c0f95c905 in Widelands::Warehouse::init(Widelands::EditorGameBase&) ../src/logic/map_objects/tribes/warehouse.cc:578
    #2 0x564c0f8214a0 in Widelands::BuildingDescr::create(Widelands::EditorGameBase&, Widelands::Player*, Widelands::Coords, bool, bool, std::vector<std::pair<unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) const ../src/logic/map_objects/tribes/building.cc:245
    #3 0x564c0f84c3d9 in Widelands::ConstructionSite::cleanup(Widelands::EditorGameBase&) ../src/logic/map_objects/tribes/constructionsite.cc:283
    #4 0x564c0f806561 in Widelands::MapObject::remove(Widelands::EditorGameBase&) ../src/logic/map_objects/map_object.cc:502
    #5 0x564c0f8065ea in Widelands::MapObject::destroy(Widelands::EditorGameBase&) ../src/logic/map_objects/map_object.cc:518
    #6 0x564c0f82406e in Widelands::Building::destroy(Widelands::EditorGameBase&) ../src/logic/map_objects/tribes/building.cc:546
    #7 0x564c0f8003f8 in Widelands::CmdDestroyMapObject::execute(Widelands::Game&) ../src/logic/map_objects/map_object.cc:58
    #8 0x564c0fce5918 in Widelands::CmdQueue::run_queue(int, unsigned int&) ../src/logic/cmd_queue.cc:121
    #9 0x564c0f008bbe in Widelands::Game::think() ../src/logic/game.cc:592
    #10 0x564c0f493058 in InteractiveBase::think() ../src/wui/interactive_base.cc:700
    #11 0x564c0f2cd5c5 in UI::Panel::do_think() ../src/ui_basic/panel.cc:506
    #12 0x564c0f2caa34 in UI::Panel::do_run() ../src/ui_basic/panel.cc:195
    #13 0x564c0ec7df51 in UI::Panel::Returncodes UI::Panel::run<UI::Panel::Returncodes>() ../src/ui_basic/panel.h:100
    #14 0x564c0f0082db in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:562
    #15 0x564c0f16b1c1 in GameHost::run() ../src/network/gamehost.cc:708
    #16 0x564c0ec65f8e in WLApplication::mainmenu_multiplayer() ../src/wlapplication.cc:1318
    #17 0x564c0ec6427b in WLApplication::mainmenu() ../src/wlapplication.cc:1157
    #18 0x564c0ec54303 in WLApplication::run() ../src/wlapplication.cc:493
    #19 0x564c0ec4fa81 in main ../src/main.cc:42
    #20 0x7fa05a37ecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
    #21 0x564c0ec4f91d in _start (/home/benedikt/wl/LP/widelands+0xec991d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/economy/portdock.h:85 in Widelands::PortDock::get_fleet() const
==40884==ABORTING
```

This bug is caused by the problem that a port is being created in a place where there is no free space for a port dock. This bug is fixed in the current development version already. 

If you want to continue playing this game with b21 you'd need to find the nearly-completed port construction site and destroy it before it completes, then it won't crash.

**Comment by tothxa** [comment]
Thank you very much!
