### ISSUE TITLE
MultilineEditbox crashes in `snap_to_char`

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4796]
https://www.widelands.org/forum/topic/5171
The crash can be reproduced with a self-built flatpak of latest master:
```
Thread 1 "widelands" received signal SIGABRT, Aborted.
0x00007ffff7520615 in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#0  0x00007ffff7520615 in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7509899 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555555702348 in std::__replacement_assert (__file=__file@entry=0x555555d331c0 "/usr/include/c++/9.3.0/bits/basic_string.h", __line=__line@entry=1067, __function=__function@entry=0x555555d33dd8 "std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _Ch"..., __condition=__condition@entry=0x555555d32fdb "__pos <= size()") at /usr/include/c++/9.3.0/x86_64-unknown-linux-gnu/bits/c++config.h:463
#3  0x000055555587d335 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[] (__pos=<optimized out>, this=<optimized out>) at ../src/ui_basic/multilineeditbox.cc:248
#4  UI::MultilineEditbox::Data::snap_to_char (cursor=<optimized out>, this=<optimized out>) at ../src/ui_basic/multilineeditbox.cc:249
#5  0x000055555587d4e4 in UI::MultilineEditbox::Data::snap_to_char (this=<optimized out>, cursor=<optimized out>) at ../src/ui_basic/multilineeditbox.cc:252
#6  0x000055555587d519 in UI::MultilineEditbox::Data::calculate_selection_boundaries (this=this@entry=0x555557786bc0, start=@0x7fffffff8cc0: 1140162560, end=@0x7fffffff8cc4: 1128136704) at /usr/include/c++/9.3.0/bits/stl_algobase.h:198
#7  0x000055555587d5f2 in UI::MultilineEditbox::Data::draw (this=0x555557786bc0, dst=..., with_caret=<optimized out>) at ../src/ui_basic/multilineeditbox.cc:155
#8  0x000055555587dad6 in UI::MultilineEditbox::draw (this=0x555557893b80, dst=...) at ../src/ui_basic/panel.h:275
#9  0x00005555558834a2 in UI::Panel::do_draw_inner (this=0x555557893b80, dst=...) at ../src/ui_basic/panel.cc:959
#10 0x00005555558833eb in UI::Panel::do_draw (this=this@entry=0x555557893b80, dst=...) at ../src/ui_basic/panel.cc:992
#11 0x000055555588347b in UI::Panel::do_draw_inner (this=0x7fffffff9aa8, dst=...) at ../src/ui_basic/panel.cc:956
#12 0x00005555558833eb in UI::Panel::do_draw (this=this@entry=0x7fffffff9aa8, dst=...) at ../src/ui_basic/panel.cc:992
#13 0x000055555588347b in UI::Panel::do_draw_inner (this=0x7fffffff9868, dst=...) at ../src/ui_basic/panel.cc:956
#14 0x00005555558833eb in UI::Panel::do_draw (this=this@entry=0x7fffffff9868, dst=...) at ../src/ui_basic/panel.cc:992
#15 0x000055555588347b in UI::Panel::do_draw_inner (this=0x7fffffff9628, dst=...) at ../src/ui_basic/panel.cc:956
#16 0x00005555558833eb in UI::Panel::do_draw (this=this@entry=0x7fffffff9628, dst=...) at ../src/ui_basic/panel.cc:992
#17 0x000055555588347b in UI::Panel::do_draw_inner (this=0x7fffffff93e8, dst=...) at ../src/ui_basic/panel.cc:956
#18 0x00005555558833eb in UI::Panel::do_draw (this=this@entry=0x7fffffff93e8, dst=...) at ../src/ui_basic/panel.cc:992
#19 0x000055555588347b in UI::Panel::do_draw_inner (this=0x7fffffff9260, dst=...) at ../src/ui_basic/panel.cc:956
#20 0x00005555558833eb in UI::Panel::do_draw (this=this@entry=0x7fffffff9260, dst=...) at ../src/ui_basic/panel.cc:992
#21 0x000055555588347b in UI::Panel::do_draw_inner (this=0x7fffffffc650, dst=...) at ../src/ui_basic/panel.cc:956
#22 0x00005555558833eb in UI::Panel::do_draw (this=this@entry=0x7fffffffc650, dst=...) at ../src/ui_basic/panel.cc:992
#23 0x0000555555884fbe in UI::Panel::do_redraw_now (this=this@entry=0x7fffffff9260) at ../src/ui_basic/panel.cc:187
#24 0x0000555555885248 in UI::Panel::do_run (this=this@entry=0x7fffffff9260) at ../src/ui_basic/panel.cc:257
#25 0x00005555558d6746 in UI::Panel::run<int> (this=0x7fffffff9260) at ../src/ui_basic/panel.h:110
#26 FsMenu::AddOnsCtrl::<lambda()>::operator()(void) const (__closure=<optimized out>) at ../src/ui_fsmenu/addons.cc:537
#27 0x0000555555867ac2 in boost::function0<void>::operator() (this=<optimized out>) at /app/include/boost/function/function_template.hpp:677
#28 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void ()> >(boost::function<void ()>&, boost::signals2::detail::unsigned_meta_array<>, std::tuple<> const&, boost::enable_if<boost::is_void<boost::function<void ()>::result_type>, void>::type*) const (this=<optimized out>, func=...) at /app/include/boost/signals2/detail/variadic_slot_invoker.hpp:117
#29 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void ()>, , 0ul>(boost::function<void ()>&, std::tuple<> const&, mpl_::size_t<0ul>) const (this=<optimized out>, args=empty std::tuple, func=...) at /app/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#30 boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) const (this=0x7fffffffb8c0, connectionBody=...) at /app/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#31 boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >::dereference() const (this=0x7fffffffb610) at /app/include/boost/signals2/detail/slot_call_iterator.hpp:110
#32 boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) (f=...) at /app/include/boost/iterator/iterator_facade.hpp:550
#33 boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (this=0x7fffffffb610) at /app/include/boost/iterator/iterator_facade.hpp:656
#34 boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >) const (last=..., first=..., this=<optimized out>) at /app/include/boost/signals2/optional_last_value.hpp:57
#35 boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >) const (this=<optimized out>, last=..., first=..., combiner=...) at /app/include/boost/signals2/detail/result_type_wrapper.hpp:64
#36 boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() (this=0x5555579790e0) at /app/include/boost/signals2/detail/signal_template.hpp:243
#37 0x0000555555864bd3 in boost::signals2::signal<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() (this=0x555557f6ecf8) at /app/include/boost/smart_ptr/shared_ptr.hpp:726
#38 UI::Button::handle_mouserelease (btn=1 '\001', this=0x555557f6ebf8) at ../src/ui_basic/button.cc:376
#39 UI::Button::handle_mouserelease (this=0x555557f6ebf8, btn=<optimized out>) at ../src/ui_basic/button.cc:365
#40 0x0000555555885983 in UI::Panel::ui_mouserelease (button=<optimized out>, x=<optimized out>, y=<optimized out>) at ../src/ui_basic/panel.cc:1332
#41 0x00005555556f8f06 in WLApplication::handle_input (this=this@entry=0x555555fdb890, cb=cb@entry=0x555555f654c0 <UI::Panel::do_run()::input_callback>) at ../src/wlapplication.cc:855
#42 0x000055555588516b in UI::Panel::do_run (this=this@entry=0x7fffffffc650) at ../src/ui_basic/panel.cc:240
#43 0x00005555556fee8f in UI::Panel::run<int> (this=0x7fffffffc650) at ../src/ui_basic/panel.h:110
#44 WLApplication::run (this=this@entry=0x555555fdb890) at ../src/wlapplication.cc:720
#45 0x00005555556872cf in main (argc=1, argv=0x7fffffffe7e8) at ../src/main.cc:47
```

**Comment by tothxa** [comment]
I can confirm that this change solved the problem. Thank you very much!
