### ISSUE TITLE
Crash when scrolling empty list of objectives up

### ISSUE THREAD

**Issue by DarthGandalf** [widelands/widelands#5029]
**Describe the bug**
Game segfaults when trying to scroll the mouse

**To Reproduce**
1. Go to list of objectives when it's empty
2. Move the mouse the the upper part of the window (where the list of objectives is), above the description of the selected objective
3. Scroll the mouse whell up (scrolling down doesn't trigger the crash)

**Expected behavior**
Nothing should happen

**Screenshots**
![Рабочий стол 1_363](https://user-images.githubusercontent.com/325092/129799216-4dfe61f1-e2ea-41b1-bba1-f8c5f02e8447.png)

**Version:**
 - OS: Gentoo Linux, amd64
 - Widelands Version: 1.0

**Additional context**
* Stack trace: [gdb.txt](https://github.com/widelands/widelands/files/7002944/gdb.txt)
* Save file: [4-12.wgf.gz](https://github.com/widelands/widelands/files/7002958/4-12.wgf.gz)

**Comment by Noordfrees** [comment]
Thanks for reporting, crash confirmed
```
widelands: ../src/ui_basic/listselect.h:84: uint32_t UI::BaseListselect::operator[](uint32_t) const: Assertion `i < size()' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff4ecc864 in __GI_abort () at abort.c:79
#2  0x00007ffff4ecc749 in __assert_fail_base
    (fmt=0x7ffff5055f78 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555557bcee40 "i < size()", file=0x555557bcee00 "../src/ui_basic/listselect.h", line=84, function=<optimised out>) at assert.c:92
#3  0x00007ffff4ede3d6 in __GI___assert_fail
    (assertion=0x555557bcee40 "i < size()", file=0x555557bcee00 "../src/ui_basic/listselect.h", line=84, function=0x555557bceda0 "uint32_t UI::BaseListselect::operator[](uint32_t) const") at assert.c:101
#4  0x0000555556a71cc6 in UI::BaseListselect::operator[](unsigned int) const (this=0x61d000193e70, i=4294967294) at ../src/ui_basic/listselect.h:84
#5  0x0000555556ab3094 in UI::Listselect<Widelands::Objective const*>::operator[](unsigned int) const (this=0x61d000193e70, i=4294967294) at ../src/ui_basic/listselect.h:197
#6  0x0000555556ab287c in UI::Listselect<Widelands::Objective const&>::operator[](unsigned int) const (this=0x61d000193e70, i=4294967294) at ../src/ui_basic/listselect.h:239
#7  0x0000555556aae5f1 in GameObjectivesMenu::selected(unsigned int) (this=0x61d000193c80, t=4294967294) at ../src/wui/game_objectives_menu.cc:95
#8  0x0000555556aad4fc in operator()(uint32_t) const (__closure=0x6060009eed20, a=4294967294) at ../src/wui/game_objectives_menu.cc:52
#9  0x0000555556aaf487 in boost::detail::function::void_function_obj_invoker1<GameObjectivesMenu::GameObjectivesMenu(UI::Panel*, UI::UniqueWindow::Registry&)::<lambda(uint32_t)>, void, unsigned int>::invoke(boost::detail::function::function_buffer &, unsigned int)Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xffffffffffffffc0: 
 (function_obj_ptr=..., a0=#10 0x00005555563c1c01 in boost::function1<void, unsigned int>::operator()(unsigned int) const
    (this=0x6060009eed18, a0=4294967294) at /usr/include/boost/function/function_template.hpp:763
#11 0x00005555563c19cf in boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (unsigned int)>, 0u, unsigned int&>(boost::function<void (unsigned int)>&, boost::signals2::detail::unsigned_meta_array<0u>, std::tuple<unsigned int&> const&, boost::enable_if<boost::is_void<boost::function<void (unsigned int)>::result_type>, void>::type*) const
    (this=0x7fffffff3710, func=..., args=std::tuple containing = {...}) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:105
#12 0x00005555563c18ee in boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (unsigned int)>, unsigned int&, 1ul>(boost::function<void (unsigned int)>&, std::tuple<unsigned int&> const&, mpl_::size_t<1ul>) const (this=0x7fffffff3710, func=..., args=std::tuple containing = {...}) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#13 0x00005555563c16da in boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > const&) const (this=0x7fffffff3eb0, connectionBody=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#14 0x00005555563c0cad in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >::dereference() const (this=0x7fffffff38d0) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
#15 0x00005555563bf93e in boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > const&) (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:550
#16 0x00005555563bef7a in boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (this=0x7fffffff38d0) at /usr/include/boost/iterator/iterator_facade.hpp:656
#17 0x00005555563bd6a8 in boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >) const (this=0x602000663910, first=..., last=...) at /usr/include/boost/signals2/optional_last_value.hpp:57
#18 0x00005555563bb604 in boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_--Type <RET> for more, q to quit, c to continue without paging--c
call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >) const (this=0x7fffffff3b60, combiner=..., first=Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xffffffffffffff60: 
#19 0x00005555563b9343 in boost::signals2::detail::signal_impl<void (unsigned int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (unsigned int)>, boost::function<void (boost::signals2::connection const&, unsigned int)>, boost::signals2::mutex>::operator()(unsigned int) (this=0x6040020bc9d0, args#0=4294967294) at /usr/include/boost/signals2/detail/signal_template.hpp:243
#20 0x00005555563b7563 in boost::signals2::signal<void (unsigned int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (unsigned int)>, boost::function<void (boost::signals2::connection const&, unsigned int)>, boost::signals2::mutex>::operator()(unsigned int) (this=0x61d000193fb8, args#0=4294967294) at /usr/include/boost/signals2/detail/signal_template.hpp:722
#21 0x00005555563af159 in UI::BaseListselect::select(unsigned int) (this=0x61d000193e70, i=4294967294) at ../src/ui_basic/listselect.cc:236
#22 0x00005555563b32f2 in UI::BaseListselect::handle_mousewheel(unsigned int, int, int) (this=0x61d000193e70, which=0, x=0, y=1) at ../src/ui_basic/listselect.cc:479
#23 0x00005555563e32c0 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) (this=0x61d000193e70, which=0, x=0, y=1, rel_mouse_pos=...) at ../src/ui_basic/panel.cc:1344
#24 0x00005555563e31c3 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) (this=0x61d000193c80, which=0, x=0, y=1, rel_mouse_pos=...) at ../src/ui_basic/panel.cc:1338
#25 0x00005555563e31c3 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) (this=0x626000af2100, which=0, x=0, y=1, rel_mouse_pos=...) at ../src/ui_basic/panel.cc:1338
#26 0x00005555563e5044 in UI::Panel::ui_mousewheel(unsigned int, int, int) (which=0, x=0, y=1) at ../src/ui_basic/panel.cc:1617
#27 0x0000555555c133b6 in WLApplication::handle_input(InputCallback const*) (this=0x6120000001c0, cb=0x55555862e220 <UI::Panel::do_run()::input_callback>) at ../src/wlapplication.cc:955
#28 0x00005555563daa2f in UI::Panel::do_run() (this=0x626000af2100) at ../src/ui_basic/panel.cc:399
#29 0x0000555555c3af74 in UI::Panel::run<UI::Panel::Returncodes>() (this=0x626000af2100) at ../src/ui_basic/panel.h:120
#30 0x00005555560baf79 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61e0001ae880, start_game_type=Widelands::Game::StartGameType::kMap, script_to_run="", replay=false, prefix_for_replays="single_player") at ../src/logic/game.cc:769
#31 0x000055555671a475 in FsMenu::LaunchSPG::clicked_ok() (this=0x627000142100) at ../src/ui_fsmenu/launch_spg.cc:171
#32 0x00005555564e52a4 in FsMenu::TwoColumnsFullNavigationMenu::handle_key(bool, SDL_Keysym) (this=0x627000142100, down=true, code=Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xffffffffffffffc0: 
#33 0x00005555563e3b2a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x627000142100, down=true, code=...) at ../src/ui_basic/panel.cc:1401
#34 0x00005555563e3a4e in UI::Panel::do_key(bool, SDL_Keysym) (this=0x7fffffffd4e8, down=true, code=...) at ../src/ui_basic/panel.cc:1393
#35 0x00005555563e3a4e in UI::Panel::do_key(bool, SDL_Keysym) (this=0x7fffffffb120, down=true, code=...) at ../src/ui_basic/panel.cc:1393
#36 0x00005555563e51f0 in UI::Panel::ui_key(bool, SDL_Keysym) (down=true, code=...) at ../src/ui_basic/panel.cc:1633
#37 0x0000555555c13172 in WLApplication::handle_input(InputCallback const*) (this=0x6120000001c0, cb=0x55555862e220 <UI::Panel::do_run()::input_callback>) at ../src/wlapplication.cc:940
#38 0x00005555563daa2f in UI::Panel::do_run() (this=0x7fffffffb120) at ../src/ui_basic/panel.cc:399
#39 0x0000555555c38f98 in UI::Panel::run<int>() (this=0x7fffffffb120) at ../src/ui_basic/panel.h:120
#40 0x0000555555c0fca0 in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:813
#41 0x0000555555c030d9 in main(int, char**) (argc=1, argv=0x7fffffffdd58) at ../src/main.cc:47
```

**Comment by tothxa** [comment]
I'll include the fix for this in my mousewheel changes. But don't wait for me if you think it's urgent.
