### ISSUE TITLE
In MP setup, changing role/flag in some cases causes host to crash

### ISSUE THREAD

**Issue by andy5995** [widelands/widelands#5341]
**Describe the bug**
While setting up an MP game, if player 2 changes his flag, player 1 (the host) crashes

**To Reproduce**
1. The steps mentioned in #5340 
2. Player 2 changes flag to red
3. host crashes

**Version:**
 - OS: Manjaro
 - Widelands Version: https://github.com/widelands/widelands/commit/386823517f8d37f777c81d9ebcdfbd11cc436344

**Additional context**
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
This is Widelands Version 1.1~git54[8c47015@master] (Debug)
[00:00:00.000 real] INFO: Set home directory: /home/andy/.local/share/widelands
[00:00:00.000 real] INFO: Set configuration file: /home/andy/.config/widelands/config
[00:00:00.001 real] INFO: Widelands executable directory: /home/andy/src/widelands/
[00:00:00.002 real] WARNING: No locale translations found in /home/andy/src/widelands/data/locale
[00:00:00.002 real] INFO: selected language: en
[00:00:00.002 real] INFO: using locale en_US.utf-8
[00:00:00.096 real] INFO: Adding directory: /home/andy/src/widelands/data
[00:00:00.098 real] INFO: selected language: en
[00:00:00.099 real] INFO: using locale en_US.utf-8
[00:00:00.106 real] INFO: Byte order: little-endian
[00:00:01.751 real] INFO: Graphics: Try to set Videomode 1600x900
[00:00:01.772 real] INFO: Graphics: OpenGL: Version "4.6.0 NVIDIA 510.54"
[00:00:01.773 real] INFO: Graphics: SDL_GL_RED_SIZE is 8
[00:00:01.773 real] INFO: Graphics: SDL_GL_GREEN_SIZE is 8
[00:00:01.773 real] INFO: Graphics: SDL_GL_BLUE_SIZE is 8
[00:00:01.773 real] INFO: Graphics: SDL_GL_ALPHA_SIZE is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_BUFFER_SIZE is 24
[00:00:01.773 real] INFO: Graphics: SDL_GL_DOUBLEBUFFER is 1
[00:00:01.773 real] INFO: Graphics: SDL_GL_DEPTH_SIZE is 24
[00:00:01.773 real] INFO: Graphics: SDL_GL_STENCIL_SIZE is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_ACCUM_RED_SIZE is 16
[00:00:01.773 real] INFO: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 16
[00:00:01.773 real] INFO: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 16
[00:00:01.773 real] INFO: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 16
[00:00:01.773 real] INFO: Graphics: SDL_GL_STEREO is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
[00:00:01.773 real] INFO: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
[00:00:01.773 real] INFO: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
[00:00:01.773 real] INFO: Graphics: SDL_GL_CONTEXT_FLAGS is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
[00:00:01.773 real] INFO: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
[00:00:01.773 real] INFO: Graphics: OpenGL: Double buffering enabled
[00:00:01.773 real] INFO: Graphics: OpenGL: Max texture size: 32768
[00:00:01.773 real] INFO: Graphics: OpenGL: ShadingLanguage: "4.60 NVIDIA"
[00:00:01.780 real] INFO: **** GRAPHICS REPORT ****
[00:00:01.780 real] INFO: VIDEO DRIVER GLVND x11
[00:00:01.780 real] INFO: Display #0: 1920x1080 @ 60hz SDL_PIXELFORMAT_RGB888
[00:00:02.122 real] INFO: **** SOUND REPORT ****
[00:00:02.122 real] INFO: SDL version: 2.0.20
[00:00:02.122 real] INFO: SDL_mixer version: 2.0.4
[00:00:02.122 real] INFO: **** END SOUND REPORT ****
[New Thread 0x7fffebf6a640 (LWP 15168)]
[New Thread 0x7fffebf29640 (LWP 15169)]
[New Thread 0x7fffe5884640 (LWP 15170)]
[00:00:07.394 real] ERROR: [BufferedConnection] Trying to connect to 2a03:4000:32:524:48cb:feff:feae:b0c6:7395 failed!
[00:00:07.394 real] ERROR: [NetClient]: Trying to connect to 2a03:4000:32:524:48cb:feff:feae:b0c6:7395 failed!
[New Thread 0x7fffe91f0640 (LWP 15197)]
[New Thread 0x7fffeb6ad640 (LWP 15200)]
[00:00:29.800 real] WARNING: Map/Save is a directory! No way for making it available a.t.m.!
/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1136: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&]: Assertion '!empty()' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
0x00007ffff4e4b34c in __pthread_kill_implementation () from /usr/lib/libc.so.6
(gdb) info stack
#0  0x00007ffff4e4b34c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007ffff4dfe4b8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff4de8534 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff518abba in std::__replacement_assert (
    __file=__file@entry=0x7ffff5271d80 "/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h", __line=__line@entry=1136, 
    __function=__function@entry=0x7ffff5274930 "std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocato"..., 
    __condition=__condition@entry=0x7ffff5271e1c "!empty()")
    at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/c++config.h:514
#4  0x00007ffff5210cc4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::back (this=<optimized out>)
    at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1136
#5  0x00005555562017b7 in GameHost::remove_player_name (this=0x60b000af0550, 
    number=0 '\000', name="Player")
    at /home/andy/src/widelands/src/network/gamehost.cc:1311
#6  0x0000555556202b76 in GameHost::switch_to_player (this=0x60b000af0550, user=1, 
    number=1 '\001') at /home/andy/src/widelands/src/network/gamehost.cc:1433
#7  0x0000555556211254 in GameHost::handle_changeposition (this=0x60b000af0550, 
    client=..., r=...) at /home/andy/src/widelands/src/network/gamehost.cc:2257
#8  0x0000555556213126 in GameHost::handle_packet (this=0x60b000af0550, client_num=0, 
--Type <RET> for more, q to quit, c to continue without paging--
    r=...) at /home/andy/src/widelands/src/network/gamehost.cc:2372
#9  0x000055555620e33a in GameHost::handle_network (this=0x60b000af0550)
    at /home/andy/src/widelands/src/network/gamehost.cc:2117
#10 0x00005555561f89de in operator() (__closure=0x7fffffff4870)
    at /home/andy/src/widelands/src/network/gamehost.cc:618
#11 0x0000555556219978 in std::__invoke_impl<void, GameHost::think()::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/11.2.0/bits/invoke.h:61
#12 0x0000555556218b72 in std::__invoke_r<void, GameHost::think()::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/11.2.0/bits/invoke.h:154
#13 0x0000555556217fad in std::_Function_handler<void(), GameHost::think()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/11.2.0/bits/std_function.h:291
#14 0x0000555555e7e5b4 in std::function<void ()>::operator()() const (
    this=0x7fffffff4870) at /usr/include/c++/11.2.0/bits/std_function.h:560
#15 0x0000555557aa6bc8 in NoteThreadSafeFunction::instantiate(std::function<void ()> const&, bool, bool) (fn=..., wait_until_completion=true, rethrow_errors=true)
    at /home/andy/src/widelands/src/base/multithreading.cc:78
#16 0x00005555561f8bd7 in GameHost::think (this=0x60b000af0550)
    at /home/andy/src/widelands/src/network/gamehost.cc:618
#17 0x00005555564745ca in FsMenu::LaunchMPG::think (this=0x629000221200)
    at /home/andy/src/widelands/src/ui_fsmenu/launch_mpg.cc:236
#18 0x00005555563db410 in UI::Panel::do_think (this=0x629000221200)
    at /home/andy/src/widelands/src/ui_basic/panel.cc:794
#19 0x00005555563db48a in UI::Panel::do_think (this=0x7fffffffd7e0)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /home/andy/src/widelands/src/ui_basic/panel.cc:810
#20 0x00005555563db48a in UI::Panel::do_think (this=0x7fffffffa750) at /home/andy/src/widelands/src/ui_basic/panel.cc:810
#21 0x00005555563d6f97 in UI::Panel::do_run (this=0x7fffffffa750) at /home/andy/src/widelands/src/ui_basic/panel.cc:412
#22 0x0000555555b489f2 in UI::Panel::run<int> (this=0x7fffffffa750) at /home/andy/src/widelands/src/ui_basic/panel.h:124
#23 0x0000555555b1ca72 in WLApplication::run (this=0x6120000001c0) at /home/andy/src/widelands/src/wlapplication.cc:817
#24 0x0000555555b0f784 in main (argc=1, argv=0x7fffffffe238) at /home/andy/src/widelands/src/main.cc:46
```

**Comment by andy5995** [comment]
I should maybe mentioned, while one may think this is a rare case, it happened to me and a friend the first time we tried playing multiplayer a couple days ago.

So... I guess my point is that you can expect that it could likely happen to new players, even though it's easy enough to prevent if you're familiar with setting up a game.
