### ISSUE TITLE
game crashed suddenly savegame not loadable

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5544]
during testplaying the game crashed suddenly and left an unloadable savegame.    
I have no glue how to reproduce.  
However just wanted to provide the savegame.   
[wl_autosave_00.zip](https://github.com/widelands/widelands/files/9484477/wl_autosave_00.zip)

**Comment by Noordfrees** [comment]
Bug in attack window saveloading code:
```gdb
[00:00:23.947 real] INFO: Game: Reading Interactive Player Data ... 
widelands: .../src/wui/attack_window.cc:501: void AttackWindow::ListOfSoldiers::remove(const Widelands::Soldier*): Assertion `it != soldiers_.end()' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737275115776) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737275115776) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737275115776) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737275115776, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff4ce7476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff4ccd7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff4ccd71b in __assert_fail_base
    (fmt=0x7ffff4e82150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555557f4f740 "it != soldiers_.end()", file=0x555557f4e0a0 ".../src/wui/attack_window.cc", line=501, function=<optimised out>) at ./assert/assert.c:92
#6  0x00007ffff4cdee96 in __GI___assert_fail
    (assertion=0x555557f4f740 "it != soldiers_.end()", file=0x555557f4e0a0 ".../src/wui/attack_window.cc", line=501, function=0x555557f4f6c0 "void AttackWindow::ListOfSoldiers::remove(const Widelands::Soldier*)") at ./assert/assert.c:101
#7  0x0000555556bc0f98 in AttackWindow::ListOfSoldiers::remove(Widelands::Soldier const*) (this=0x61500042a480, s=0x6130000f1300) at .../src/wui/attack_window.cc:501
#8  0x0000555556bc1c1e in AttackWindow::load(FileRead&, InteractiveBase&, Widelands::MapObjectLoader&) (fr=..., ib=..., mol=...) at .../src/wui/attack_window.cc:553
#9  0x00005555569d7008 in InteractiveBase::load_windows(FileRead&, Widelands::MapObjectLoader&) (this=0x629000465200, fr=..., mol=...) at .../src/wui/interactive_base.cc:972
#10 0x00005555575afa7e in Widelands::GameInteractivePlayerPacket::read(FileSystem&, Widelands::Game&, Widelands::MapObjectLoader*) (this=0x7fffffff1df0, fs=..., game=..., mol=0x60d000373820)
    at .../src/game_io/game_interactive_player_packet.cc:114
#11 0x000055555757ab19 in Widelands::GameLoader::load_game(bool) (this=0x7fffffff24a0, multiplayer=false) at .../src/game_io/game_loader.cc:185
#12 0x0000555556093e21 in Widelands::Game::run_load_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61e000117080, filename="save/5544.wgf", script_to_run="") at .../src/logic/game.cc:499
#13 0x000055555650e560 in FsMenu::LoadGame::clicked_ok() (this=0x6260003a8100) at .../src/ui_fsmenu/loadgame.cc:189
#14 0x000055555650add1 in operator()(unsigned int) const (__closure=0x606000152af8) at .../src/ui_fsmenu/loadgame.cc:88
#15 0x0000555556511912 in std::__invoke_impl<void, FsMenu::LoadGame::LoadGame(FsMenu::MenuCapsule&, Widelands::Game&, GameSettingsProvider&, bool, bool, const std::function<void(const std::__cxx11::basic_string<char>&)>&)::<lambda(unsigned int)>&, unsigned int>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#16 0x00005555565109a6 in std::__invoke_r<void, FsMenu::LoadGame::LoadGame(FsMenu::MenuCapsule&, Widelands::Game&, GameSettingsProvider&, bool, bool, const std::function<void(const std::__cxx11::basic_string<char>&)>&)::<lambda(unsigned int)>&, unsigned int>(struct {...} &) (__fn=...) at /usr/include/c++/11/bits/invoke.h:154
#17 0x000055555650fd01 in std::_Function_handler<void(unsigned int), FsMenu::LoadGame::LoadGame(FsMenu::MenuCapsule&, Widelands::Game&, GameSettingsProvider&, bool, bool, const std::function<void(const std::__cxx11::basic_string<char>&)>&)::<lambda(unsigned int)> >::_M_invoke(const std::_Any_data &, unsigned int &&) (__functor=..., __args#0=@0x7fffffff31f0: 2) at /usr/include/c++/11/bits/std_function.h:290
#18 0x0000555555e2c508 in std::function<void (unsigned int)>::operator()(unsigned int) const (this=0x606000152af8, __args#0=2) at /usr/include/c++/11/bits/std_function.h:590
#19 0x00005555560fb848 in Notifications::Signal<unsigned int>::operator()(unsigned int) const (this=0x6180000cc6a8, args#0=2) at .../src/notifications/signal.h:62
#20 0x00005555564b2876 in UI::Table<void*>::handle_key(bool, SDL_Keysym)Python Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0xffffffffffffffc2
 (this=0x6180000cc480, down=true, code=#21 0x0000555556461675 in UI::Panel::do_key(bool, SDL_Keysym)
    (this=0x6180000cc480, down=true, code=...) at .../src/ui_basic/panel.cc:1401
#22 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x6150003efb00, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#23 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x6260003a8be0, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#24 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x6260003a8a08, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#25 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x6260003a8648, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#26 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x6260003a8470, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#27 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x6260003a8298, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#28 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x6260003a8100, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#29 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x7fffffffd2b8, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#30 0x000055555646153a in UI::Panel::do_key(bool, SDL_Keysym) (this=0x7fffffffa1d0, down=true, code=...) at .../src/ui_basic/panel.cc:1393
#31 0x0000555556463108 in UI::Panel::ui_key(bool, SDL_Keysym) (down=true, code=...) at .../src/ui_basic/panel.cc:1647
#32 0x0000555555b40a42 in WLApplication::handle_input(InputCallback const*) (this=0x6120000001c0, cb=0x555558966e20 <UI::Panel::do_run()::input_callback>) at .../src/wlapplication.cc:962
#33 0x0000555556457712 in UI::Panel::do_run() (this=0x7fffffffa1d0) at .../src/ui_basic/panel.cc:389
#34 0x0000555555b6a20a in UI::Panel::run<int>() (this=0x7fffffffa1d0) at .../src/ui_basic/panel.h:125
#35 0x0000555555b3d763 in WLApplication::run() (this=0x6120000001c0) at .../src/wlapplication.cc:841
#36 0x0000555555b2fd97 in main(int, char**) (argc=2, argv=0x7fffffffdd08) at .../src/main.cc:45
```
```gdb
(gdb) up 8
#8  0x0000555556bc1c1e in AttackWindow::load (fr=..., ib=..., mol=...) at .../src/wui/attack_window.cc:553
553					a->remaining_soldiers_->remove(s);
(gdb) p s
$1 = (const Widelands::Soldier *) 0x6130000f1300
(gdb) p a->remaining_soldiers_
$2 = std::unique_ptr<AttackWindow::ListOfSoldiers> = {get() = 0x61500042a480}
(gdb) p a->attacking_soldiers_
$3 = std::unique_ptr<AttackWindow::ListOfSoldiers> = {get() = 0x61500042a700}
(gdb) p i
$4 = 1
```
