### ISSUE TITLE
Segfault With Invalid Battle After Saveloading

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5882]
**Describe the bug**
The attached savegame crashes with a nullptr dereference in soldier code.

**To reproduce**
1. Load this savegame: 
[TiperarySoldierCrash.wgf.zip](https://github.com/widelands/widelands/files/11357155/TiperarySoldierCrash.wgf.zip)
2. Wait until gametime 33:32:07.518 (only a few seconds)
3. Segfault. Does not happen every time, but about four out of five.

**Expected behavior**
No crash

**Version:**
 - OS: Debian Unstable
 - Widelands Version: 1.2~git26126 (2d94dd6@master) Release

**Additional context**
Last output from `--verbose` and GDB backtrace:
```gdb
[33:32:07.518 game] DEBUG: MO(10613,frisians_soldier): [defense] starting battle with 10732!

Thread 11 "widelands" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde40d6c0 (LWP 363880)]
0x000055555618538d in Widelands::Map::calc_distance (this=0x61e00010ecf8, a=..., b=...) at .../src/logic/map.cc:1891
1891		dy = b.y - a.y;
(gdb) bt
#0  0x000055555618538d in Widelands::Map::calc_distance(Widelands::Coords const&, Widelands::Coords const&) const (this=0x61e00010ecf8, a=..., b=...) at .../src/logic/map.cc:1891
#1  0x0000555556bafde8 in Widelands::Soldier::check_node_blocked(Widelands::Game&, Widelands::FCoords const&, bool) (this=0x613000a07440, game=..., field=..., commit=false)
    at .../src/logic/map_objects/tribes/soldier.cc:1662
#2  0x0000555556a153a3 in Widelands::BlockedTracker::is_blocked(Widelands::FCoords const&) (this=0x7fffde40c2c0, field=...) at .../src/logic/map_objects/bob.cc:476
#3  0x0000555556a1573f in Widelands::CheckStepBlocked::allowed(Widelands::Map const&, Widelands::FCoords, Widelands::FCoords, int, Widelands::CheckStep::StepId) const (this=0x60200268c998, end=...)
    at .../src/logic/map_objects/bob.cc:505
#4  0x0000555556a1f2d3 in Widelands::CheckStep::Capsule<Widelands::CheckStepBlocked>::allowed(Widelands::Map const&, Widelands::FCoords const&, Widelands::FCoords const&, int, Widelands::CheckStep::StepId) const (this=0x60200268c990, map=..., start=..., end=..., dir=5, id=Widelands::CheckStep::stepFirst) at .../src/logic/map_objects/checkstep.h:57
#5  0x0000555556197be8 in Widelands::CheckStep::allowed(Widelands::Map const&, Widelands::FCoords const&, Widelands::FCoords const&, int, Widelands::CheckStep::StepId) const
    (this=0x60300418d9c0, map=..., start=..., end=..., dir=5, id=Widelands::CheckStep::stepFirst) at .../src/logic/map_objects/checkstep.h:87
#6  0x0000555556a1fa0e in operator()(Widelands::CheckStep const&) const (__closure=0x7fffde40b750, cstep=...) at .../src/logic/map_objects/checkstep.cc:67
#7  0x0000555556a241b8 in __gnu_cxx::__ops::_Iter_negate<Widelands::CheckStepAnd::allowed(const Widelands::Map&, const Widelands::FCoords&, const Widelands::FCoords&, int32_t, Widelands::CheckStep::StepId) const::<lambda(const Widelands::CheckStep&)> >::operator()<__gnu_cxx::__normal_iterator<const Widelands::CheckStep*, std::vector<Widelands::CheckStep> > >(__gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >) (this=0x7fffde40b750, __it=<error reading variable: Cannot access memory at address 0x2378>)
    at /usr/include/c++/12/bits/predefined_ops.h:395
#8  0x0000555556a232f0 in std::__find_if<__gnu_cxx::__normal_iterator<const Widelands::CheckStep*, std::vector<Widelands::CheckStep> >, __gnu_cxx::__ops::_Iter_negate<Widelands::CheckStepAnd::allowed(const Widelands::Map&, const Widelands::FCoords&, const Widelands::FCoords&, int32_t, Widelands::CheckStep::StepId) const::<lambda(const Widelands::CheckStep&)> > >(__gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, __gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, __gnu_cxx::__ops::_Iter_negate<Widelands::CheckStepAnd::allowed(const Widelands::Map&, const Widelands::FCoords&, const Widelands::FCoords&, int32_t, Widelands::CheckStep::StepId) const::<lambda(const Widelands::CheckStep&)> >, std::random_access_iterator_tag) (__first=..., __last=..., __pred=...) at /usr/include/c++/12/bits/stl_algobase.h:2097
#9  0x0000555556a222fa in std::__find_if_not<__gnu_cxx::__normal_iterator<const Widelands::CheckStep*, std::vector<Widelands::CheckStep> >, __gnu_cxx::__ops::_Iter_pred<Widelands::CheckStepAnd::allowed(const Widelands::Map&, const Widelands::FCoords&, const Widelands::FCoords&, int32_t, Widelands::CheckStep::StepId) const::<lambda(const Widelands::CheckStep&)> > >(__gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, __gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, __gnu_cxx::__ops::_Iter_pred<Widelands::CheckStepAnd::allowed(const Widelands::Map&, const Widelands::FCoords&, const Widelands::FCoords&, int32_t, Widelands::CheckStep::StepId) const::<lambda(const Widelands::CheckStep&)> >) (__first=..., __last=..., __pred=...) at /usr/include/c++/12/bits/stl_algo.h:109
#10 0x0000555556a218ef in std::find_if_not<__gnu_cxx::__normal_iterator<const Widelands::CheckStep*, std::vector<Widelands::CheckStep> >, Widelands::CheckStepAnd::allowed(const Widelands::Map&, const Widelands::FCoords&, const Widelands::FCoords&, int32_t, Widelands::CheckStep::StepId) const::<lambda(const Widelands::CheckStep&)> >(__gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, __gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, struct {...})
    (__first=..., __last=..., __pred=...) at /usr/include/c++/12/bits/stl_algo.h:516
#11 0x0000555556a21221 in std::all_of<__gnu_cxx::__normal_iterator<const Widelands::CheckStep*, std::vector<Widelands::CheckStep> >, Widelands::CheckStepAnd::allowed(const Widelands::Map&, const Widelands::FCoords&, const Widelands::FCoords&, int32_t, Widelands::CheckStep::StepId) const::<lambda(const Widelands::CheckStep&)> >(__gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, __gnu_cxx::__normal_iterator<Widelands::CheckStep const*, std::vector<Widelands::CheckStep, std::allocator<Widelands::CheckStep> > >, struct {...})
    (__first=..., __last=..., __pred=...) at /usr/include/c++/12/bits/stl_algo.h:456
#12 0x0000555556a1faa1 in Widelands::CheckStepAnd::allowed(Widelands::Map const&, Widelands::FCoords const&, Widelands::FCoords const&, int, Widelands::CheckStep::StepId) const
    (this=0x6030041abfb8, map=..., start=..., end=..., dir=5, id=Widelands::CheckStep::stepFirst) at .../src/logic/map_objects/checkstep.cc:65
#13 0x000055555670ae73 in Widelands::CheckStep::Capsule<Widelands::CheckStepAnd>::allowed(Widelands::Map const&, Widelands::FCoords const&, Widelands::FCoords const&, int, Widelands::CheckStep::StepId) const
    (this=0x6030041abfb0, map=..., start=..., end=..., dir=5, id=Widelands::CheckStep::stepFirst) at .../src/logic/map_objects/checkstep.h:57
#14 0x0000555556197be8 in Widelands::CheckStep::allowed(Widelands::Map const&, Widelands::FCoords const&, Widelands::FCoords const&, int, Widelands::CheckStep::StepId) const
    (this=0x7fffde40c1e0, map=..., start=..., end=..., dir=5, id=Widelands::CheckStep::stepFirst) at .../src/logic/map_objects/checkstep.h:87
#15 0x0000555556187e7f in Widelands::Map::findpath(Widelands::Coords, Widelands::Coords, int, Widelands::Path&, Widelands::CheckStep const&, unsigned int, unsigned int, Widelands::WareWorker) const
    (this=0x61e00010ecf8, instart=..., inend=..., persist=3, path=..., checkstep=..., flags=0, caps_sensitivity=0, type=Widelands::wwWORKER) at .../src/logic/map.cc:2259
#16 0x0000555556a08c34 in Widelands::Bob::start_task_movepath(Widelands::Game&, Widelands::Coords const&, int, DirAnimations const&, bool, int, bool)
    (this=0x613000a07440, game=..., dest=..., persist=3, anims=..., forceonlast=false, only_step=1, forceall=false) at .../src/logic/map_objects/bob.cc:548
#17 0x0000555556bab654 in Widelands::Soldier::defense_update(Widelands::Game&, Widelands::Bob::State&) (this=0x613000a07440, game=..., state=...)
    at .../src/logic/map_objects/tribes/soldier.cc:1305
#18 0x0000555556a06899 in Widelands::Bob::do_act(Widelands::Game&) (this=0x613000a07440, game=...) at .../src/logic/map_objects/bob.cc:197
#19 0x0000555556a064c5 in Widelands::Bob::act(Widelands::Game&, unsigned int) (this=0x613000a07440, game=..., data=3977) at .../src/logic/map_objects/bob.cc:176
#20 0x0000555556a9c6c3 in Widelands::CmdAct::execute(Widelands::Game&) (this=0x603007fb13f0, game=...) at .../src/logic/map_objects/map_object.cc:106
#21 0x0000555557141367 in Widelands::CmdQueue::run_queue(Duration const&, Time&) (this=0x61e00010f5d0, interval=..., game_time_var=...) at .../src/logic/cmd_queue.cc:121
#22 0x0000555556068f00 in Widelands::Game::think() (this=0x61e00010ec80) at .../src/logic/game.cc:871
#23 0x00005555566a689b in InteractiveBase::game_logic_think() (this=0x629000adc200) at .../src/wui/interactive_base.cc:830
#24 0x00005555563adc6f in UI::Panel::logic_thread() () at .../src/ui_basic/panel.cc:198
#25 0x0000555555c71147 in std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) (__f=@0x602000088878: 0x5555563ada5e <UI::Panel::logic_thread()>) at /usr/include/c++/12/bits/invoke.h:61
--Type <RET> for more, q to quit, c to continue without paging--c
#26 0x0000555555c6ff28 in std::__invoke<void (*)()>(void (*&&)()) (__fn=@0x602000088878: 0x5555563ada5e <UI::Panel::logic_thread()>) at /usr/include/c++/12/bits/invoke.h:96
#27 0x0000555555c6efd6 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x602000088878) at /usr/include/c++/12/bits/std_thread.h:252
#28 0x0000555555c6e31c in std::thread::_Invoker<std::tuple<void (*)()> >::operator()() (this=0x602000088878) at /usr/include/c++/12/bits/std_thread.h:259
#29 0x0000555555c6dc18 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() (this=0x602000088870) at /usr/include/c++/12/bits/std_thread.h:210
#30 0x00007ffff4ed44a3 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#31 0x00007ffff50a7fd4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#32 0x00007ffff51285bc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) p a
$1 = (const Widelands::Coords &) <error reading variable: Cannot access memory at address 0x78>
(gdb) p &a
$2 = (const Widelands::Coords *) 0x78
(gdb) p &b
$3 = (const Widelands::Coords *) 0x6130007c5938
(gdb) up
#1  0x0000555556bafde8 in Widelands::Soldier::check_node_blocked (this=0x613000a07440, game=..., field=..., commit=false) at .../src/logic/map_objects/tribes/soldier.cc:1662
1662				    game.map().calc_distance(soldier->get_battle()->first()->get_position(),
(gdb) p soldier
$4 = (Widelands::Soldier * const) 0x6130007c58c0
(gdb) p soldier->get_battle()
$5 = (Widelands::Battle *) 0x60e0003f04a0
(gdb) p soldier->get_battle()->first()
$6 = (Widelands::Soldier *) 0x0
```

**Comment by Noordfrees** [comment]
The bug does not appear to happen when loading the savegame with #5869
