### ISSUE TITLE
Python scripts in workflows fail with "autopep8"→"packaging" dependency error

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#6119]
**Describe the bug**
`fix_formatting.py` fails in workflow runs. It looks like a dependency error.

**To reproduce**
1. See workflow log of any new commit

**Expected behavior**
Script runs through. :)

**Additional context**
Log:
```
Run python3 ./utils/fix_formatting.py
Traceback (most recent call last):
  File "/home/runner/work/widelands/widelands/./utils/fix_formatting.py", line 25, in <module>
    import autopep8
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/autopep8.py", line 87, in <module>
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging'
Error: Process completed with exit code 1.
```

**Comment by tothxa** [comment]
Looks like `packaging` is a nw dependency of `autopep8`, so we need to add that to the setup. Also affected today's translations run, so all workflow scripts must be checked.

I will try to do it, but only in the evening, so not assigning myself yet.

**Comment by tothxa** [comment]
Hmm, maybe it'll get fixed [upstream](https://github.com/hhatto/autopep8/issues/702) sooner or later?

**Comment by tothxa** [comment]
Fixed in new upstream release. They dropped the unintentionally introduced new dependency. Workflow formatting runs are green again.
