### ISSUE TITLE
Naval Warfare: Save game crashes randomly

### ISSUE THREAD

**Issue by carli2** [widelands/widelands#6121]
Sometimes it crashes, sometimes not.
```
[04:37:01.021 game] WARNING:  2:ship on 140x108 received scout command but not in kExpeditionWaiting or kExpeditionPortspaceFound or kExpeditionScouting status (expedition: N), ignoring...
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1185334==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000050 (pc 0x55be8248ad0f bp 0x7ffc6df472a0 sp 0x7ffc6df47290 T0)
==1185334==The signal is caused by a READ memory access.
==1185334==Hint: address points to the zero page.
    #0 0x55be8248ad0f in Widelands::MapObject::descr() const /home/carli/projekte/widelands/src/logic/map_objects/map_object.h:186
    #1 0x55be8364000c in Widelands::MapObjectSaver::get_object_record(Widelands::MapObject const&) /home/carli/projekte/widelands/src/map_io/map_object_saver.cc:45
    #2 0x55be83640f58 in Widelands::MapObjectSaver::get_object_file_index(Widelands::MapObject const&) /home/carli/projekte/widelands/src/map_io/map_object_saver.cc:130
    #3 0x55be83602054 in Widelands::MapBuildingdataPacket::write_warehouse(Widelands::Warehouse const&, FileWrite&, Widelands::Game&, Widelands::MapObjectSaver&) /home/carli/projekte/widelands/src/map_io/map_buildingdata_packet.cc:1300
    #4 0x55be835ff927 in Widelands::MapBuildingdataPacket::write(FileSystem&, Widelands::EditorGameBase&, Widelands::MapObjectSaver&) /home/carli/projekte/widelands/src/map_io/map_buildingdata_packet.cc:1110
    #5 0x55be83688e98 in Widelands::MapSaver::save() /home/carli/projekte/widelands/src/map_io/map_saver.cc:275
    #6 0x55be83a10004 in Widelands::GameMapPacket::write(FileSystem&, Widelands::Game&, Widelands::MapObjectSaver*) /home/carli/projekte/widelands/src/game_io/game_map_packet.cc:64
    #7 0x55be83a25590 in Widelands::GameSaver::save() /home/carli/projekte/widelands/src/game_io/game_saver.cc:77
    #8 0x55be8315b4c0 in operator() /home/carli/projekte/widelands/src/wui/game_main_menu_save_game.cc:304
    #9 0x55be83160132 in __invoke_impl<void, GameMainMenuSaveGame::save_game(std::string, bool)::<lambda(FileSystem&)>&, FileSystem&> /usr/include/c++/11/bits/invoke.h:61
    #10 0x55be8315f72e in __invoke_r<void, GameMainMenuSaveGame::save_game(std::string, bool)::<lambda(FileSystem&)>&, FileSystem&> /usr/include/c++/11/bits/invoke.h:111
    #11 0x55be8315e367 in _M_invoke /usr/include/c++/11/bits/std_function.h:290
    #12 0x55be83f210b0 in std::function<void (FileSystem&)>::operator()(FileSystem&) const /usr/include/c++/11/bits/std_function.h:590
    #13 0x55be83f1ad54 in GenericSaveHandler::save_file() /home/carli/projekte/widelands/src/logic/generic_save_handler.cc:99
    #14 0x55be83f1ba30 in GenericSaveHandler::save() /home/carli/projekte/widelands/src/logic/generic_save_handler.cc:154
    #15 0x55be8315c20a in GameMainMenuSaveGame::save_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) /home/carli/projekte/widelands/src/wui/game_main_menu_save_game.cc:310
    #16 0x55be8315ac98 in GameMainMenuSaveGame::ok() /home/carli/projekte/widelands/src/wui/game_main_menu_save_game.cc:225
    #17 0x55be83156f4b in operator() /home/carli/projekte/widelands/src/wui/game_main_menu_save_game.cc:133
    #18 0x55be8315fb67 in __invoke_impl<void, GameMainMenuSaveGame::GameMainMenuSaveGame(InteractiveGameBase&, UI::UniqueWindow::Registry&, GameMainMenuSaveGame::Type)::<lambda()>&> /usr/include/c++/11/bits/invoke.h:61
    #19 0x55be8315e869 in __invoke_r<void, GameMainMenuSaveGame::GameMainMenuSaveGame(InteractiveGameBase&, UI::UniqueWindow::Registry&, GameMainMenuSaveGame::Type)::<lambda()>&> /usr/include/c++/11/bits/invoke.h:111
    #20 0x55be8315daae in _M_invoke /usr/include/c++/11/bits/std_function.h:290
    #21 0x55be8257a901 in std::function<void ()>::operator()() const /usr/include/c++/11/bits/std_function.h:590
    #22 0x55be825762b1 in Notifications::Signal<>::operator()() const /home/carli/projekte/widelands/src/notifications/signal.h:62
    #23 0x55be82bc03cf in UI::EditBox::handle_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/textinput.cc:827
    #24 0x55be82b47a24 in UI::Panel::do_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1405
    #25 0x55be82b478e9 in UI::Panel::do_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1397
    #26 0x55be82b478e9 in UI::Panel::do_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1397
    #27 0x55be82b478e9 in UI::Panel::do_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1397
    #28 0x55be82b478e9 in UI::Panel::do_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1397
    #29 0x55be82b478e9 in UI::Panel::do_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1397
    #30 0x55be82b49334 in UI::Panel::ui_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1663
    #31 0x55be822c2c21 in WLApplication::handle_input(InputCallback const*) /home/carli/projekte/widelands/src/wlapplication.cc:968
    #32 0x55be82b3dcb1 in UI::Panel::do_run() /home/carli/projekte/widelands/src/ui_basic/panel.cc:404
    #33 0x55be83159346 in GameMainMenuSaveGame::GameMainMenuSaveGame(InteractiveGameBase&, UI::UniqueWindow::Registry&, GameMainMenuSaveGame::Type) /home/carli/projekte/widelands/src/wui/game_main_menu_save_game.cc:160
    #34 0x55be82ebd7d5 in InteractiveGameBase::handle_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/wui/interactive_gamebase.cc:515
    #35 0x55be82efc0b6 in InteractivePlayer::handle_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/wui/interactive_player.cc:914
    #36 0x55be82b47a24 in UI::Panel::do_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1405
    #37 0x55be82b49334 in UI::Panel::ui_key(bool, SDL_Keysym) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1663
    #38 0x55be822c2c21 in WLApplication::handle_input(InputCallback const*) /home/carli/projekte/widelands/src/wlapplication.cc:968
    #39 0x55be82b3dcb1 in UI::Panel::do_run() /home/carli/projekte/widelands/src/ui_basic/panel.cc:404
    #40 0x55be822ea275 in UI::Panel::Returncodes UI::Panel::run<UI::Panel::Returncodes>() /home/carli/projekte/widelands/src/ui_basic/panel.h:148
    #41 0x55be827ba747 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/carli/projekte/widelands/src/logic/game.cc:779
    #42 0x55be829913fc in GameHost::run_callback() /home/carli/projekte/widelands/src/network/gamehost.cc:614
    #43 0x55be8298e4dd in operator() /home/carli/projekte/widelands/src/network/gamehost.cc:471
    #44 0x55be829b04ad in __invoke_impl<void, GameHost::run()::<lambda()>&> /usr/include/c++/11/bits/invoke.h:61
    #45 0x55be829afd05 in __invoke_r<void, GameHost::run()::<lambda()>&> /usr/include/c++/11/bits/invoke.h:111
    #46 0x55be829af7ae in _M_invoke /usr/include/c++/11/bits/std_function.h:290
    #47 0x55be8257a901 in std::function<void ()>::operator()() const /usr/include/c++/11/bits/std_function.h:590
    #48 0x55be82be6018 in FsMenu::LaunchMPG::clicked_ok() /home/carli/projekte/widelands/src/ui_fsmenu/launch_mpg.cc:252
    #49 0x55be82c53f35 in operator() /home/carli/projekte/widelands/src/ui_fsmenu/menu.cc:170
    #50 0x55be82c59769 in __invoke_impl<void, FsMenu::TwoColumnsFullNavigationMenu::TwoColumnsFullNavigationMenu(FsMenu::MenuCapsule&, const string&, double)::<lambda()>&> /usr/include/c++/11/bits/invoke.h:61
    #51 0x55be82c59119 in __invoke_r<void, FsMenu::TwoColumnsFullNavigationMenu::TwoColumnsFullNavigationMenu(FsMenu::MenuCapsule&, const string&, double)::<lambda()>&> /usr/include/c++/11/bits/invoke.h:111
    #52 0x55be82c58ae6 in _M_invoke /usr/include/c++/11/bits/std_function.h:290
    #53 0x55be8257a901 in std::function<void ()>::operator()() const /usr/include/c++/11/bits/std_function.h:590
    #54 0x55be825762b1 in Notifications::Signal<>::operator()() const /home/carli/projekte/widelands/src/notifications/signal.h:62
    #55 0x55be82b0488e in UI::Button::handle_mouserelease(unsigned char, int, int) /home/carli/projekte/widelands/src/ui_basic/button.cc:381
    #56 0x55be82b47413 in UI::Panel::do_mouserelease(unsigned char, int, int) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1366
    #57 0x55be82b48d76 in UI::Panel::ui_mouserelease(unsigned char, int, int) /home/carli/projekte/widelands/src/ui_basic/panel.cc:1587
    #58 0x55be822c40e0 in WLApplication::handle_mousebutton(SDL_Event&, InputCallback const*) /home/carli/projekte/widelands/src/wlapplication.cc:1072
    #59 0x55be822c2d64 in WLApplication::handle_input(InputCallback const*) /home/carli/projekte/widelands/src/wlapplication.cc:979
    #60 0x55be82b3dcb1 in UI::Panel::do_run() /home/carli/projekte/widelands/src/ui_basic/panel.cc:404
    #61 0x55be82c47521 in int UI::Panel::run<int>() /home/carli/projekte/widelands/src/ui_basic/panel.h:148
    #62 0x55be82c27d68 in FsMenu::MainMenu::main_loop() /home/carli/projekte/widelands/src/ui_fsmenu/main.cc:246
    #63 0x55be822c0511 in WLApplication::run() /home/carli/projekte/widelands/src/wlapplication.cc:847
    #64 0x55be822b0edb in main /home/carli/projekte/widelands/src/main.cc:113
    #65 0x7f95af229d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #66 0x7f95af229e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #67 0x55be822b0d04 in _start (/home/carli/projekte/widelands/widelands+0x6b5d04)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/carli/projekte/widelands/src/logic/map_objects/map_object.h:186 in Widelands::MapObject::descr() const
==1185334==ABORTING

```

**Comment by Noordfrees** [comment]
Duplicate of #6118
