### ISSUE TITLE
stack-buffer-underflow when Player is Joining MP game

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#6131]
When playing the NavalWarwarfare Tournmanent @Noordfrees  joined my hosted game
provoking an immediate crash. Next time, playing with Tayeo all was fine,
so I assume this is some Race condition?

No idea how to reproduce this, yet
**Version:**
 - OS: macOS Vetura 13.5 / Apple M1 Pro CPU aka ARM or Apple Silicon.
 - Widelands Version: 1.2~git26395 (7b7b190@HEAD) 

```
==57691==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x00016ce2c1ff at pc 0x000103c97930 bp 0x00016ce2c1d0 sp 0x00016ce2c1c8
READ of size 1 at 0x00016ce2c1ff thread T0
    #0 0x103c9792c in GameHost::remove_player_name(unsigned char, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) gamehost.cc:1337
    #1 0x103c938fc in GameHost::switch_to_player(unsigned int, unsigned char) gamehost.cc:1463
    #2 0x103ca8cf8 in GameHost::handle_changeposition(Client const&, RecvPacket&) gamehost.cc:2301
    #3 0x103ca6720 in GameHost::handle_packet(unsigned int, RecvPacket&) gamehost.cc:2427
    #4 0x103ca4e84 in GameHost::handle_network() gamehost.cc:2161
    #5 0x103ce7788 in GameHost::think()::$_1::operator()() const gamehost.cc:644
```

more in Attached file [Crash.txt](https://github.com/widelands/widelands/files/12473050/Crash.txt)

**Comment by klaus-halfmann** [comment]
Maybe this jsut the same only at the End of the MP game
[Crash3.txt](https://github.com/widelands/widelands/files/12476217/Crash3.txt)
