### ISSUE TITLE
crash reports with master

### ISSUE THREAD

**Issue by SimonHeimberg** [widelands/widelands#6200]
**Describe the bug**
With a version close to current master, I got several crash reports.

**To reproduce**
I send the crash reports in separate messages (similar ones in one message).
I play "poor hamlet" and "struggling outpost" and test a script (which enables and disables buildings and ...).

**Version:**
 - OS: "Debian bookworm"
 - Widelands Version: 1.2~git26353 (9919cd6@pr-6030) Debug (merged with master, about f73563aa1c3f)

**Additional context**
I finally managed to compile and start widelands

**Comment by SimonHeimberg** [comment]
Memory access violation

# Autogenerated crash report for 2 crash(es):

- 2023-10-24T21.43.25.txt
- 2023-10-26T09.12.23.txt

## Technical report:
> Version: 1.2~git26353 (9919cd6@pr-6030) Debug  
> Operating System: Linux  
> Compiled with SDL version: 2.26.5  
> SDL video driver: x11  
> Locale: de_CH.UTF-8  
> Home Directory: /home/simon/.local/share/widelands  
> Configuration File: /home/simon/.config/widelands/config  
> Data Directory: /home/simon/src/widelands-div/edit-github/data  
> Locale Directory: /home/simon/src/widelands-div/edit-github/data/locale  
> Executable Directory: /home/simon/src/widelands-div/edit-github/  


## crash/2023-10-24T21.43.25.txt

```
Crash report for Widelands 1.2~git26353 (9919cd6@pr-6030) Debug at 2023-10-24T21.43.25, signal 11 (Speicherzugriffsfehler)

**** BEGIN BACKTRACE ****
./widelands-div/edit-github/widelands(+0xe28588)[0x561aad0ea588]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0)[0x7f294d65afd0]
**** END BACKTRACE ****
```


## crash/2023-10-26T09.12.23.txt

```
Crash report for Widelands 1.2~git26353 (9919cd6@pr-6030) Debug at 2023-10-26T09.12.23, signal 11 (Speicherzugriffsfehler)

**** BEGIN BACKTRACE ****
./widelands-div/edit-github/widelands(+0xe28588)[0x560d93763588]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0)[0x7f1c1db7bfd0]
**** END BACKTRACE ****
```

**Comment by SimonHeimberg** [comment]
Memory access violation, very long traceback

# Autogenerated crash report for 1 crash(es):

- 2023-10-26T13.06.24.txt

## Technical report:
> Version: 1.2~git26353 (9919cd6@pr-6030) Debug  
> Operating System: Linux  
> Compiled with SDL version: 2.26.5  
> SDL video driver: x11  
> Locale: de_CH.UTF-8  
> Home Directory: /home/simon/.local/share/widelands  
> Configuration File: /home/simon/.config/widelands/config  
> Data Directory: /home/simon/src/widelands-div/edit-github/data  
> Locale Directory: /home/simon/src/widelands-div/edit-github/data/locale  
> Executable Directory: /home/simon/src/widelands-div/edit-github/  


## crash/2023-10-26T13.06.24.txt

```
Crash report for Widelands 1.2~git26353 (9919cd6@pr-6030) Debug at 2023-10-26T13.06.24, signal 11 (Speicherzugriffsfehler)

**** BEGIN BACKTRACE ****
./widelands-div/edit-github/widelands(+0xe28588)[0x55e6ada63588]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0)[0x7fa92fc5afd0]
./widelands-div/edit-github/widelands(_ZNKSt6vectorIN2UI5TableIPvE11EntryRecord4DataESaIS5_EE4sizeEv+0xc)[0x55e6ade40068]
./widelands-div/edit-github/widelands(_ZN2UI5TableIPvE11EntryRecord11set_pictureEhPK5ImageRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2e)[0x55e6ade3b932]
./widelands-div/edit-github/widelands(_ZN20ProductionSiteWindow19update_worker_tableEPN9Widelands14ProductionSiteE+0x5c2)[0x55e6adfe5dfe]
./widelands-div/edit-github/widelands(_ZN20ProductionSiteWindow5thinkEv+0x110)[0x55e6adfe580c]
./widelands-div/edit-github/widelands(_ZN2UI5Panel8do_thinkEv+0x7a)[0x55e6ade1d6bc]
./widelands-div/edit-github/widelands(_ZN2UI5Panel8do_thinkEv+0xbc)[0x55e6ade1d6fe]
./widelands-div/edit-github/widelands(_ZN2UI5Panel6do_runEv+0x3fc)[0x55e6ade1c2ec]
./widelands-div/edit-github/widelands(_ZN2UI5Panel3runINS0_11ReturncodesEEET_v+0x18)[0x55e6ada7dc52]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game3runENS0_13StartGameTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0xf5b)[0x55e6adca6533]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game13run_load_gameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_+0x514)[0x55e6adca53b0]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game3runENS0_13StartGameTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0x1295)[0x55e6adca686d]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game13run_load_gameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_+0x514)[0x55e6adca53b0]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game3runENS0_13StartGameTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0x1295)[0x55e6adca686d]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game13run_load_gameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_+0x514)[0x55e6adca53b0]
./widelands-div/edit-github/widelands(_ZN6FsMenu8LoadGame10clicked_okEv+0x2f8)[0x55e6ade65898]
./widelands-div/edit-github/widelands(+0x12296a8)[0x55e6ade646a8]
./widelands-div/edit-github/widelands(+0x122b9ea)[0x55e6ade669ea]
./widelands-div/edit-github/widelands(+0x122b4f5)[0x55e6ade664f5]
./widelands-div/edit-github/widelands(+0x122b041)[0x55e6ade66041]
./widelands-div/edit-github/widelands(_ZNKSt8functionIFvjEEclEj+0x48)[0x55e6adb8d0a4]
./widelands-div/edit-github/widelands(_ZNK13Notifications6SignalIJjEEclEj+0x76)[0x55e6adccf798]
./widelands-div/edit-github/widelands(_ZN2UI5TableIPvE17handle_mousepressEhii+0x179)[0x55e6ade3a377]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x164)[0x55e6ade1f158]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13do_mousepressEhii+0x100)[0x55e6ade1f0f4]
./widelands-div/edit-github/widelands(_ZN2UI5Panel13ui_mousepressEhii+0x129)[0x55e6ade1fd21]
./widelands-div/edit-github/widelands(_ZN13WLApplication18handle_mousebuttonER9SDL_EventPK13InputCallback+0x91)[0x55e6ada6d26f]
./widelands-div/edit-github/widelands(_ZN13WLApplication12handle_inputEPK13InputCallback+0x2d4)[0x55e6ada6cd72]
./widelands-div/edit-github/widelands(_ZN2UI5Panel6do_runEv+0x2ec)[0x55e6ade1c1dc]
./widelands-div/edit-github/widelands(_ZN2UI5Panel3runIiEET_v+0x18)[0x55e6ade8b610]
./widelands-div/edit-github/widelands(_ZN6FsMenu8MainMenu9main_loopEv+0x22)[0x55e6ade7cc36]
./widelands-div/edit-github/widelands(_ZN13WLApplication3runEv+0x719)[0x55e6ada6bdd3]
./widelands-div/edit-github/widelands(main+0x110)[0x55e6ada63acf]
/lib/x86_64-linux-gnu/libc.so.6(+0x271ca)[0x7fa92fc461ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85)[0x7fa92fc46285]
./widelands-div/edit-github/widelands(_start+0x21)[0x55e6ada63491]
**** END BACKTRACE ****

**Comment by SimonHeimberg** [comment]
memory access violation, shorter traceback

# Autogenerated crash report for 2 crash(es):


## crash/2023-10-26T18.43.34.txt

```
Crash report for Widelands 1.2~git26353 (9919cd6@pr-6030) Debug at 2023-10-26T18.43.34, signal 11 (Speicherzugriffsfehler)

**** BEGIN BACKTRACE ****
./widelands-div/edit-github/widelands(+0xe28588)[0x56530f41e588]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0)[0x7facbda5afd0]
./widelands-div/edit-github/widelands(_ZN2UI3Box13set_item_sizeEjii+0x9c)[0x56530f7b0c6a]
./widelands-div/edit-github/widelands(_ZN2UI3Box16update_positionsEv+0x167)[0x56530f7b063d]
./widelands-div/edit-github/widelands(_ZN2UI3Box6layoutEv+0x65e)[0x56530f7b045c]
./widelands-div/edit-github/widelands(_ZN2UI3Box19update_desired_sizeEv+0x265)[0x56530f7afc05]
./widelands-div/edit-github/widelands(_ZN2UI3Box3addEPNS_5PanelENS0_8ResizingENS_5AlignE+0xec)[0x56530f7b08e2]
./widelands-div/edit-github/widelands(_ZN14BuildingWindow18create_capsbuttonsEPN2UI3BoxEPN9Widelands8BuildingE+0x668)[0x56530fa1d4c6]
./widelands-div/edit-github/widelands(_ZN14BuildingWindow5thinkEv+0x185)[0x56530fa1c49b]
./widelands-div/edit-github/widelands(_ZN20ProductionSiteWindow5thinkEv+0x1b)[0x56530f9a0717]
./widelands-div/edit-github/widelands(_ZN2UI5Panel8do_thinkEv+0x7a)[0x56530f7d86bc]
./widelands-div/edit-github/widelands(_ZN2UI5Panel8do_thinkEv+0xbc)[0x56530f7d86fe]
./widelands-div/edit-github/widelands(_ZN2UI5Panel6do_runEv+0x3fc)[0x56530f7d72ec]
./widelands-div/edit-github/widelands(_ZN2UI5Panel3runINS0_11ReturncodesEEET_v+0x18)[0x56530f438c52]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game3runENS0_13StartGameTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0xf5b)[0x56530f661533]
./widelands-div/edit-github/widelands(_ZN6FsMenu9LaunchSPG10clicked_okEv+0xa7a)[0x56530f8b6c18]
./widelands-div/edit-github/widelands(+0x12560b3)[0x56530f84c0b3]
./widelands-div/edit-github/widelands(+0x12588d0)[0x56530f84e8d0]
./widelands-div/edit-github/widelands(+0x125840a)[0x56530f84e40a]
./widelands-div/edit-github/widelands(+0x1257f8b)[0x56530f84df8b]
./widelands-div/edit-github/widelands(_ZNKSt8functionIFvvEEclEv+0x32)[0x56530f55dc86]
./widelands-div/edit-github/widelands(_ZNK13Notifications6SignalIJEEclEv+0x6e)[0x56530f55c4f4]
./widelands-div/edit-github/widelands(_ZN2UI6Button19handle_mousereleaseEhii+0x95)[0x56530f7b60d5]
./widelands-div/edit-github/widelands(_ZN2UI5Panel15do_mousereleaseEhii+0x110)[0x56530f7da45e]
./widelands-div/edit-github/widelands(_ZN2UI5Panel15ui_mousereleaseEhii+0x68)[0x56530f7dad8c]
./widelands-div/edit-github/widelands(_ZN13WLApplication18handle_mousebuttonER9SDL_EventPK13InputCallback+0x11e)[0x56530f4282fc]
./widelands-div/edit-github/widelands(_ZN13WLApplication12handle_inputEPK13InputCallback+0x2d4)[0x56530f427d72]
./widelands-div/edit-github/widelands(_ZN2UI5Panel6do_runEv+0x2ec)[0x56530f7d71dc]
./widelands-div/edit-github/widelands(_ZN2UI5Panel3runIiEET_v+0x18)[0x56530f846610]
./widelands-div/edit-github/widelands(_ZN6FsMenu8MainMenu9main_loopEv+0x22)[0x56530f837c36]
./widelands-div/edit-github/widelands(_ZN13WLApplication3runEv+0x719)[0x56530f426dd3]
./widelands-div/edit-github/widelands(main+0x110)[0x56530f41eacf]
/lib/x86_64-linux-gnu/libc.so.6(+0x271ca)[0x7facbda461ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85)[0x7facbda46285]
./widelands-div/edit-github/widelands(_start+0x21)[0x56530f41e491]
**** END BACKTRACE ****
```


## crash/2023-10-26T19.00.03.txt

```
Crash report for Widelands 1.2~git26353 (9919cd6@pr-6030) Debug at 2023-10-26T19.00.03, signal 11 (Speicherzugriffsfehler)

**** BEGIN BACKTRACE ****
./widelands-div/edit-github/widelands(+0xe28588)[0x55dbf9d51588]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0)[0x7f3409a5afd0]
./widelands-div/edit-github/widelands(_ZN2UI3Box13set_item_sizeEjii+0x9c)[0x55dbfa0e3c6a]
./widelands-div/edit-github/widelands(_ZN2UI3Box16update_positionsEv+0x167)[0x55dbfa0e363d]
./widelands-div/edit-github/widelands(_ZN2UI3Box6layoutEv+0x65e)[0x55dbfa0e345c]
./widelands-div/edit-github/widelands(_ZN2UI3Box19update_desired_sizeEv+0x265)[0x55dbfa0e2c05]
./widelands-div/edit-github/widelands(_ZN2UI3Box3addEPNS_5PanelENS0_8ResizingENS_5AlignE+0xec)[0x55dbfa0e38e2]
./widelands-div/edit-github/widelands(_ZN14BuildingWindow18create_capsbuttonsEPN2UI3BoxEPN9Widelands8BuildingE+0x668)[0x55dbfa3504c6]
./widelands-div/edit-github/widelands(_ZN14BuildingWindow5thinkEv+0x185)[0x55dbfa34f49b]
./widelands-div/edit-github/widelands(_ZN20ProductionSiteWindow5thinkEv+0x1b)[0x55dbfa2d3717]
./widelands-div/edit-github/widelands(_ZN2UI5Panel8do_thinkEv+0x7a)[0x55dbfa10b6bc]
./widelands-div/edit-github/widelands(_ZN2UI5Panel8do_thinkEv+0xbc)[0x55dbfa10b6fe]
./widelands-div/edit-github/widelands(_ZN2UI5Panel6do_runEv+0x3fc)[0x55dbfa10a2ec]
./widelands-div/edit-github/widelands(_ZN2UI5Panel3runINS0_11ReturncodesEEET_v+0x18)[0x55dbf9d6bc52]
./widelands-div/edit-github/widelands(_ZN9Widelands4Game3runENS0_13StartGameTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0xf5b)[0x55dbf9f94533]
./widelands-div/edit-github/widelands(_ZN6FsMenu9LaunchSPG10clicked_okEv+0xa7a)[0x55dbfa1e9c18]
./widelands-div/edit-github/widelands(+0x12560b3)[0x55dbfa17f0b3]
./widelands-div/edit-github/widelands(+0x12588d0)[0x55dbfa1818d0]
./widelands-div/edit-github/widelands(+0x125840a)[0x55dbfa18140a]
./widelands-div/edit-github/widelands(+0x1257f8b)[0x55dbfa180f8b]
./widelands-div/edit-github/widelands(_ZNKSt8functionIFvvEEclEv+0x32)[0x55dbf9e90c86]
./widelands-div/edit-github/widelands(_ZNK13Notifications6SignalIJEEclEv+0x6e)[0x55dbf9e8f4f4]
./widelands-div/edit-github/widelands(_ZN2UI6Button19handle_mousereleaseEhii+0x95)[0x55dbfa0e90d5]
./widelands-div/edit-github/widelands(_ZN2UI5Panel15do_mousereleaseEhii+0x110)[0x55dbfa10d45e]
./widelands-div/edit-github/widelands(_ZN2UI5Panel15ui_mousereleaseEhii+0x68)[0x55dbfa10dd8c]
./widelands-div/edit-github/widelands(_ZN13WLApplication18handle_mousebuttonER9SDL_EventPK13InputCallback+0x11e)[0x55dbf9d5b2fc]
./widelands-div/edit-github/widelands(_ZN13WLApplication12handle_inputEPK13InputCallback+0x2d4)[0x55dbf9d5ad72]
./widelands-div/edit-github/widelands(_ZN2UI5Panel6do_runEv+0x2ec)[0x55dbfa10a1dc]
./widelands-div/edit-github/widelands(_ZN2UI5Panel3runIiEET_v+0x18)[0x55dbfa179610]
./widelands-div/edit-github/widelands(_ZN6FsMenu8MainMenu9main_loopEv+0x22)[0x55dbfa16ac36]
./widelands-div/edit-github/widelands(_ZN13WLApplication3runEv+0x719)[0x55dbf9d59dd3]
./widelands-div/edit-github/widelands(main+0x110)[0x55dbf9d51acf]
/lib/x86_64-linux-gnu/libc.so.6(+0x271ca)[0x7f3409a461ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85)[0x7f3409a46285]
./widelands-div/edit-github/widelands(_start+0x21)[0x55dbf9d51491]
**** END BACKTRACE ****
```

**Comment by SimonHeimberg** [comment]
And output of another build (earlier), which has asan enabled. (Not sure if widelands has crashed then. The lines before tell nothing at all about starting or ending a game.)

Are you interested in output like this one?
Is with asan more helpful than without?
I had the impression that the game crashes more frequently, so tried hard and disabled it.

```
This is Widelands version 1.2~git26351 (60142a6@HEAD) Debug
...
[00:02:11.944 real] INFO: Songset: Loaded song "music/menu.ogg"
[00:03:09.855 real] ERROR: Could not resolve network name 'widelands.org:7388' to IPv4-address: resolve: Host not found (authoritative)
[00:04:19.832 real] INFO: Songset: Loaded song "music/menu.ogg"
ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred
[00:04:58.749 real] INFO: Songset: Loaded song "music/ingame_18.ogg"
[00:06:06.782 real] INFO: Songset: Loaded song "music/ingame_25.ogg"
[00:09:53.086 real] INFO: Songset: Loaded song "music/ingame_06.ogg"
=================================================================
==635821==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020003ad294 at pc 0x7fbd4b84a731 bp 0x7fff9c4e4090 sp 0x7fff9c4e3840
READ of size 5 at 0x6020003ad294 thread T0
    #0 0x7fbd4b84a730 in __interceptor_strlen ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:389
    #1 0x7fbd494c81da  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xa11da)
    #2 0x7fbd49532313  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x10b313)
    #3 0x7fbd495330ea  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x10c0ea)
    #4 0x7fbd4947d382  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x56382)
    #5 0x7fbd4947d719  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x56719)
    #6 0x5638ae743550 in WLApplication::poll_event(SDL_Event&) const /home/wl/src/src/wlapplication.cc:882
    #7 0x5638ae743fe3 in WLApplication::handle_input(InputCallback const*) /home/wl/src/src/wlapplication.cc:970
    #8 0x5638aeaf31cb in UI::Panel::do_run() /home/wl/src/src/ui_basic/panel.cc:395
    #9 0x5638ae754c51 in UI::Panel::Returncodes UI::Panel::run<UI::Panel::Returncodes>() /home/wl/src/src/ui_basic/panel.h:148
    #10 0x5638ae97d522 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/wl/src/src/logic/game.cc:778
    #11 0x5638aebd2bf1 in FsMenu::LaunchSPG::clicked_ok() /home/wl/src/src/ui_fsmenu/launch_spg.cc:185
    #12 0x5638aeb6808c in operator() /home/wl/src/src/ui_fsmenu/menu.cc:169
    #13 0x5638aeb6a8a9 in __invoke_impl<void, FsMenu::TwoColumnsFullNavigationMenu::TwoColumnsFullNavigationMenu(FsMenu::MenuCapsule&, const std::string&, double)::<lambda()>&> /usr/include/c++/12/bits/invoke.h:61
    #14 0x5638aeb6a3e3 in __invoke_r<void, FsMenu::TwoColumnsFullNavigationMenu::TwoColumnsFullNavigationMenu(FsMenu::MenuCapsule&, const std::string&, double)::<lambda()>&> /usr/include/c++/12/bits/invoke.h:111
    #15 0x5638aeb69f64 in _M_invoke /usr/include/c++/12/bits/std_function.h:290
    #16 0x5638ae879c75 in std::function<void ()>::operator()() const /usr/include/c++/12/bits/std_function.h:591
    #17 0x5638ae8784e3 in Notifications::Signal<>::operator()() const /home/wl/src/src/notifications/signal.h:62
    #18 0x5638aead20c4 in UI::Button::handle_mouserelease(unsigned char, int, int) /home/wl/src/src/ui_basic/button.cc:381
    #19 0x5638aeaf644d in UI::Panel::do_mouserelease(unsigned char, int, int) /home/wl/src/src/ui_basic/panel.cc:1357
    #20 0x5638aeaf6d7b in UI::Panel::ui_mouserelease(unsigned char, int, int) /home/wl/src/src/ui_basic/panel.cc:1578
    #21 0x5638ae7442fb in WLApplication::handle_mousebutton(SDL_Event&, InputCallback const*) /home/wl/src/src/wlapplication.cc:1091
    #22 0x5638ae743d71 in WLApplication::handle_input(InputCallback const*) /home/wl/src/src/wlapplication.cc:998
    #23 0x5638aeaf31cb in UI::Panel::do_run() /home/wl/src/src/ui_basic/panel.cc:395
    #24 0x5638aeb625e9 in int UI::Panel::run<int>() /home/wl/src/src/ui_basic/panel.h:148
    #25 0x5638aeb53c0f in FsMenu::MainMenu::main_loop() /home/wl/src/src/ui_fsmenu/main.cc:246
    #26 0x5638ae742dd2 in WLApplication::run() /home/wl/src/src/wlapplication.cc:866
    #27 0x5638ae73aace in main /home/wl/src/src/main.cc:113
    #28 0x7fbd490461c9  (/lib/x86_64-linux-gnu/libc.so.6+0x271c9)
    #29 0x7fbd49046284 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27284)
    #30 0x5638ae73a490 in _start (/home/simon/src/widelands-div/edit-github/widelands+0xe21490)

0x6020003ad294 is located 0 bytes to the right of 4-byte region [0x6020003ad290,0x6020003ad294)
allocated by thread T0 here:
    #0 0x7fbd4b8b89cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fbd494c7822  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xa0822)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:389 in __interceptor_strlen
Shadow bytes around the buggy address:
  0x0c048006da00: fa fa fa fa fa fa fa fa fa fa fd fd fa fa fa fa
  0x0c048006da10: fa fa fd fd fa fa fd fa fa fa 00 00 fa fa fa fa
  0x0c048006da20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00 00
  0x0c048006da30: fa fa fa fa fa fa fa fa fa fa fd fa fa fa 00 00
  0x0c048006da40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c048006da50: fa fa[04]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048006da60: fa fa 00 fa fa fa fd fd fa fa fd fd fa fa 00 00
  0x0c048006da70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fd
  0x0c048006da80: fa fa fd fd fa fa fa fa fa fa 00 00 fa fa fa fa
  0x0c048006da90: fa fa 00 00 fa fa fd fd fa fa fd fd fa fa fa fa
  0x0c048006daa0: fa fa 00 00 fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==635821==ABORTING
```

**Comment by klaus-halfmann** [comment]
Uhm, do have some private branch I can check? 
https://github.com/widelands/widelands/commit/9919cd6063f918a7221d7abcc841b6f5148bcf06 
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by tothxa** [comment]
@klaus-halfmann 
> Why did the Bunnybot remove my Tags?

https://codeberg.org/wl/GithubCodebergMirror/issues/12
It happens when you both add a comment and modify tags in a short time. (between 2 bunnybot passes?)

**Comment by SimonHeimberg** [comment]
> Uhm, do have some private branch I can check? [9919cd6](https://github.com/widelands/widelands/commit/9919cd6063f918a7221d7abcc841b6f5148bcf06)
> 
> > This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

This is in GH pr #6030

**Comment by SimonHeimberg** [comment]
> Hello @SimonHeimberg thanks for reporting these Bugs. Some general comments about reporting.

Hello @klaus-halfmann
Sorry for my late replay. Where I live most of the year, I am only online infrequently, kind of like visiting an internet cafe.

>
>     * Never mix Versions in one Bug, please (AFAI see this is not the case here)
>
>     * In case you know these are not related please make separate bugs
>
>     * Whenever possible try to reproduce with ASAN. The Bug reports are way more detailed then without and often pin down the bug exactly.
>

Good to know. I can not read those reports.
Unfortunately I can not reproduce.
>     * Yes, ASAN will slow down the game but only for huge games like in the current tournament.
>

Will there also be more crashes with ASAN? This was my impression, but maybe it was statistical jitter only.

>     * You are testing a very edgy case "poor hamlet" and "struggling outpost"  are difficult for the AI and if a script manipulates this, matters are getting worse.

The ai can not start successfully with those. It will sure waist some resources for "poor hanmlet" start condition.
What does script make worse?

>     * Please set Autosave to 5 Minutes or even lower and attach the Savegames and/or Replay, this helps a lot in reproducing such Bugs.

Replay is not recorded because the extension is marked as "desync".

I reduced auto save time. And I try to remember to write a note directly after a crash (what happened last in case I am aware of, which save game), so that I can provide more information later when I go online.

>
>     * Please provide the script you are using and a detailed description how you start widelands with the script.
>
>     * The APIs exposed to LUA may expose Bugs that can not be reproduced by normal gameplay.
>
I am aware. I know many ways to crash widelands with ui and scripting ;-) :
- open a buildings window, then set `thisBuilding.distruction_blocked = true` from script (or set it to false when it was forbidden)
- open construction window (lets say on a small place), then set `interactivePlayer.forbid_buildings({"one_of_players_small_buildings"})` (no crash in case you are on another tab)

>     * In case this script is not only for "playing around" you might pack it as extension.
>

I have packed "explorer wins" and other extensions. This one is definitely not ready.

> I have some vacation these days, so we can have a chat in https://meet.ffmuc.net/WidelandsChat please contact me via the website for a time and Date. I will try to make something out of the infos you provided meanwhile.
>

> From what I can deduce (DE: Kafeesatzlesen) from the Stacktraces they are mostly related to UI Elements being displayed or manipulated, this usually happens due to multithreading Issues. e.g. your scripts removes a building while
some information panels is displayed. This needs carefull usage of mutexes and such. Please add some debug output to your script so we may put this in context.

I can imagine you are right with interference between ui and script. This is why don't have windows open when I use this script. (Maybe I forgot one?)
My script already contains a lot of debug output. But I still have no idea where the crash happens. Even with a savegame a bit before, I do not manage to reprouce a crash.

Maybe being on a branch changing ui (for lua mainly, but anyway) and running a script which does too much I can tell where it was is too much at once.

> Ant thanks again for helping us developing this game.

**Comment by tothxa** [comment]
> This is in GH pr https://github.com/widelands/widelands/pull/6030

Well, I don't think you should open bugs for open PRs. Please report them directly in the PR's discussion instead.

> Will there also be more crashes with ASAN?

Yes, it will catch memory handling errors even if they don't produce noticeable effects. If you also build with the debug option, then also all `assert()`s will actually do the checks, which are normally "preprocessed out" in "release" builds.

> The ai can not start successfully with those. It will sure waist some resources for "poor hanmlet" start condition. What does script make worse?

I can imagine that there could be problems if you disable some building type while it is being built somewhere? Not sure if you do that though under "enabling and disabling buildings".

**Comment by SimonHeimberg** [comment]
> I am aware. I know many ways to crash widelands with ui and scripting ;-) :
>
>    open a buildings window, then set thisBuilding.distruction_blocked = true from script (or set it to false when it was forbidden)

Any interest in a traceback (with asan) of this? I doubt this happens in scenarios, win conditions or usual scripts.

**Comment by SimonHeimberg** [comment]
Memory leaks detected by asan are not to be reported, right?

**Comment by tothxa** [comment]
> Any interest in a traceback (with asan) of this? I doubt this happens in scenarios, win conditions or usual scripts.

If you have a script that can trigger a crash in master or navalwarfare, then you should post that first of all in a new bug report. The asan log may also be included in the "Additional Context" section.

> Memory leaks detected by asan are not to be reported, right?

AFAIK we only have one known leak in SDL, so any other one (in master or navalwarfare) is a regression that should be reported. (in a new bug :)

If you have either of the above only in a PR branch, then please report it in the PR's discussion.

**Comment by SimonHeimberg** [comment]
I created a new bug report, with asan enabled.

I think I have asked all related questions now. :see_no_evil:

I suggest to mark this issue as "invalid" and close it. But I do not find a matching label.
